apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: observability
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:0q1KhyYiq/N42X5q+wS7JAwJttAEzfEVsx3tIUOxTQUwr0SEBt5j/4w0hilskenpnHZnAWBH7icc2H/2aSfEbxandzeD85I43LCKfFhRmIyqkKot8MFyhpAo,iv:wDoseKle4WFyzSbpQZhfcSAgGpeKWQ10su3NxjzAG/I=,tag:d/GsGDXEespBVdehmdOs8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZHFRVzd0SXJGNGpCbFBE
            dVdkbzB5Nncwc3UwTm1DME1ySmdFcGhvNkFzCldoN2h6RXZ2NURLOFEzWjI1bmtQ
            cVh1RnVyK3FYMjhBWHJSZ2hEUHcxbncKLS0tIDMrN2R4WTZPTEx4Z3dlMm9Edkpl
            QkRLZGE3VHpQNVZMcVliT004WExJd3MKUUm6/fZV9d8ELBh6/QZtO9uQRKE+ZeZI
            K8YmMHguIOUOssTQoQECJgkzKa3Z0KeDjH3rr9f1STFnkshy7qJhfQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T16:20:52Z"
    mac: ENC[AES256_GCM,data:sqvwWqj4ZMFMaO03sIpEcS7q8soptkq+cYYtieYaIEwFQwBl0V9O1pHfRUFM0NImBrmmUFr9CnlmxcrY99YySGLPN/1hBiu47WmjOeGrNSBrGU1kWwr6KQT6EVkUEPOMCyiDHFjXdKYUHM1DSsPkwoSbbzIP33sH47f5ZLHtKVY=,iv:wngmVag/CX4s8kIrdBMqp8Coje2o31y20CMF6EKN6ac=,tag:gHQy9IEBIGBv33jXC9Fpjw==,type:str]
    version: 3.13.3
