apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-smtp
    namespace: observability
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:h2HlLDr1mBdgJf/VCKZOsU6MXWSBVRMnDHKSmgGLXG9ycJKyP0QOZkejrGdYmzmP2IXKN9baKQByuG+fdznD5T1Ux6YxZ/ReZyhnjkTOhpUrxF/DmQht2IPr,iv:SGRkw1SzPw29aKRgtVayjN8VHLaXuHOIXDk2wdQgeBo=,tag:tWcvmxcLPw5okEjwu1fTpg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNi9zWW1QaVZ4NzJsa094
            V1k0czNycWF1TzlIRUNHMCtBQ1liY01sMEFvClNBWm13UkZmVDlNZWdjY1g0cGFj
            OEd5YUhHZEIxaGljc0RqOS9KSXB4aFkKLS0tIGFHWHZIL0JyVmdFV3dnV1AzWHNM
            SEduSWFSSzZxN3VXMFFiSE52ZDZkR0kKRr4SrgzEJng89JI5reDkBZJWE5dbRr+Y
            Mex2QdFsCsChTpsnn35DzO6gXTRV1Bmg5vmWDlrNvoEO8XtvpNSICw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T18:02:15Z"
    mac: ENC[AES256_GCM,data:KCGWa+J4q+TXEnqgQnBfK6NfDErAn/BJAjylBRVzKJPP4spTA4T5aDsU/A5DptJwxhn5AQ24jALBH3GMec7/mFUC/MuR993zdaHZQADW7WWbaBQSsZPaKN3GR5Pra62xVfNfCvPN2NSV/vHUyH1nzBuSWrO5GmXtGQvb+8Q5Sg4=,iv:pyjPtbHB1axtizptkia/wNqY3eS7zpEFjmXGH05MYAU=,tag:iDf9lGGNdu0TYr46WJPhEg==,type:str]
    version: 3.13.3
