apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: ingress-nginx
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6xVAjX1wIokZi25kAUA56vqegMgZjXm4E8QPKpuxC0RqjkHRgOcT9LCxtGWP6rsrmkKUCw17MKBIpzyqzvJ1sNysrRSqfV38ZIwhITVcxxuZDU4pDtNert4d+qgXSw/GrYEE/VJSimG7QhIZiRb3+SjOGxPmialGQO6VFgALufR9XSZvUr2iqjgNBVkokz1yLo72lpuE8MGkukThxv8bIXsjbp6UwTmHqSrqXNisRT/pCqWCNQiIUyzWu9Mdy36MbhQDluf5GvF8GH3rwZTkxi+MHhHSAkHAJ4NRR+3O/z66Qz3MOVbJ/fA6kcpEwWN7,iv:g8sX9NclfbgV1swOO9l9dGpl7DstNARCJrWYgY+gYRI=,tag:oGB/aeLcK26/JeoUpPsZeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzeDk1WWlBbGF0VFZiM25h
            UkVxL3lhRHdmME1MNmRoSVp2cUZBRkJLc1hnCjFOSEN0czRta3BjeURVU1RxMDIy
            VUVVb0xOK2x0bElXZ0hLR3Y3Q2xibXMKLS0tIEw2THoyV0Y5M1RnR1FwbGorREhP
            aXpQYy9RYzlIRUd6S0F4ZGJNWm9mVk0KBke8mzLgzEFf4+vzeLSIOA6wnDCo+oDX
            SZ/lqIxxyO3P85nbAEnZRmNeg6XP9e/Jd26Ul/BN/WtehY01hz+dlw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T17:23:33Z"
    mac: ENC[AES256_GCM,data:xP+aAfepNQq6NiuQOYye3HfudK6QSzxyZHt85GAutj6f5vF4S0lPI4hP/rBIDnRruWxGwqTNteRfqWdq5u6VQczt7X+XoOCRdKJ1qpN2Jamnv15VUf8oSyux8bY4RDqQnZhF3JtnIXNijOunl0NBq8GN62EHEcp/VINLy8AsbfI=,iv:56B2lLIoPjoOLpEv3HuQs96gWY59wEbwLtX1CYt9PPI=,tag:9TVLFQwwyZGCIO3NKyWVug==,type:str]
    version: 3.13.3
