apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:I08o4oUdogNGrEhNHHHhPEmxxy2+d46x53dedAPLhaI4JKKiO28s0EAXcVXFtndgdMSiANQ=,iv:IpRgIfNV+w0UGhkObcVb9KBBtqM0Y03lnJxi70B7MiA=,tag:H5n7BDfNQqBdP/CBLCmbRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4UHBaNGlGSGg3ZnUwRUVK
            bHhHeFJuQmFuU2pPVzUrTDQydE4ybWNQWEFnCkM5RHdZVVg1TmpVbmtWS3AvYmla
            QnhEb2U1OEY5VlVQN2duYUpxTHl3WnMKLS0tIENRN2V0bm44SWlldVdlNU9NVlZH
            cGwvdnk4UUMva3RUT3pNaHptSVgzR2sK1psDxVcki/+ckXFSFi+0ip3voF3R8Bq1
            YLiG5gTxOv8vGpIqRhr2kUslQoxgnj9f24rtXRdhyOyWPz4MCuKtEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNjBDcDZjOVdYMkpwYnRz
            anE5U2hCT1huRmFHbnY0cUdrSjRYRE1pZ3hVCmF6S1NzVS9GWXJHaUVOSzNBanJq
            eElydUlOaDdEMHFDalU0bisvY3lqNXcKLS0tIHJEWDhxL0R4QWJibEh4RHZXdDIr
            S0FJbG5DWUQwTVZGbyttTEdadXBxT1UKUI82wcP3hsV8dNCsHiZyb4ydCRwtzpGe
            BmU8e6dcuVEDQAV6an4lxKq9+C2oaQEnvHhwmSffmiD9bePtKuQ1Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T16:07:04Z"
    mac: ENC[AES256_GCM,data:u7mDGilxUneQM/X1ssDkajnuC5ACGRPYgAbshHZHcwUo7Aejz+x/sl+yEgYLbKQhd0Cx8lF2mTg6XRC6UUewyPlE/AvA0DoUQ0gWTkaLXnvEyD5U4sTUkUIRV0M4Wcts+QwNAzCXiAlYX2SekaNlPFYhaEWp5/O8DnceKVHcP5s=,iv:f4uTSRCCktWANKKbd1I7MQ5nkVZG3yebJiPcaGKVbD0=,tag:ZmBJ/M1YqzLW9k6pPA+Ryw==,type:str]
    version: 3.13.3
