apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-token
    namespace: ingress-nginx
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6xVAjX1wIokZi25kAUA56vqegMgZjXm4E8QPKpuxC0RqjkHRgOcT9LCxtGWP6rsrmkKUCw17MKBIpzyqzvJ1sNysrRSqfV38ZIwhITVcxxuZDU4pDtNert4d+qgXSw/GrYEE/VJSimG7QhIZiRb3+SjOGxPmialGQO6VFgALufR9XSZvUr2iqjgNBVkokz1yLo72lpuE8MGkukThxv8bIXsjbp6UwTmHqSrqXNisRT/pCqWCNQiIUyzWu9Mdy36MbhQDluf5GvF8GH3rwZTkxi+MHhHSAkHAJ4NRR+3O/z66Qz3MOVbJ/fA6kcpEwWN7,iv:g8sX9NclfbgV1swOO9l9dGpl7DstNARCJrWYgY+gYRI=,tag:oGB/aeLcK26/JeoUpPsZeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TWhrT0t5UFh1c0xBMVpD
            SUFuYWVETklGalJUY1RuS0FIb0JuV0Nwc2lZCmY4eXhyQkJ5VnJJVFBGUjF4K0dN
            c0hBdXpNZXVGMjVFcEFwcEUzcjJUOXcKLS0tIE5zSjQzYldvNUZ0ZjJyaG5CKzhs
            WEFla3VaamdBNWt1SHZ2OVNjZk1FU28KlSXnWCMiZf8VaPhZd0izYprzl5OUiHXH
            7Z77xQd0XGKK4A5x7NRWm2SRGTmx0aPeRCB0H+dVkeQ3JVLBrXSWSA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcmtkdVF2eWFCeUJYRkNI
            cUhUV20xN2paZGgyWkgzQnRVTHllaU5SeWlFCkxlNlFBeVAzVjEyWjZHbGV5Mndh
            WVovdWRFN0hGRjBpU0NQY3YvVU5qb3MKLS0tIHZmVVJOVmcrM3VOUVhzak9sMTdC
            YldQdTFFS0owdUdWSnlZRWprMnlTcmsKUYNHvDwmZrjcMzv2tefbfu+5J5MisZwY
            dyVi+vJfrTLL/A9IunDZo03Wzg9I3k4SO+o5dRWVLe1232K24TVb/Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T17:23:33Z"
    mac: ENC[AES256_GCM,data:xP+aAfepNQq6NiuQOYye3HfudK6QSzxyZHt85GAutj6f5vF4S0lPI4hP/rBIDnRruWxGwqTNteRfqWdq5u6VQczt7X+XoOCRdKJ1qpN2Jamnv15VUf8oSyux8bY4RDqQnZhF3JtnIXNijOunl0NBq8GN62EHEcp/VINLy8AsbfI=,iv:56B2lLIoPjoOLpEv3HuQs96gWY59wEbwLtX1CYt9PPI=,tag:9TVLFQwwyZGCIO3NKyWVug==,type:str]
    version: 3.13.3
