apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:I08o4oUdogNGrEhNHHHhPEmxxy2+d46x53dedAPLhaI4JKKiO28s0EAXcVXFtndgdMSiANQ=,iv:IpRgIfNV+w0UGhkObcVb9KBBtqM0Y03lnJxi70B7MiA=,tag:H5n7BDfNQqBdP/CBLCmbRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSVQvSFdTOU1ESm1PQnBW
            REFYT1Jza2p1OVk2ejlLakhlZmQxcWtwTFRRCnVrck5SeUg0MnlxbzVsemtMRVl5
            aEVFQklWKzl2RTY3dUhna1g1bnRuaEkKLS0tIDFrUlcwVFNYM0NDV0dLenJLa0gy
            UTczZlFMRUl2NjZSZEZUcXZOYkRxYnMKBITVkmqTp+zTeBVjRNlQw7PiIBkdNioS
            OYSCrTNsuPVlPKb4o9a5W0iVuAr/PDToT65VR4ijy+HybjXRO+Dy3Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T16:07:04Z"
    mac: ENC[AES256_GCM,data:u7mDGilxUneQM/X1ssDkajnuC5ACGRPYgAbshHZHcwUo7Aejz+x/sl+yEgYLbKQhd0Cx8lF2mTg6XRC6UUewyPlE/AvA0DoUQ0gWTkaLXnvEyD5U4sTUkUIRV0M4Wcts+QwNAzCXiAlYX2SekaNlPFYhaEWp5/O8DnceKVHcP5s=,iv:f4uTSRCCktWANKKbd1I7MQ5nkVZG3yebJiPcaGKVbD0=,tag:ZmBJ/M1YqzLW9k6pPA+Ryw==,type:str]
    version: 3.13.3
