apiVersion: v1
kind: Secret
metadata:
    name: core-db
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MN2uHQ==,iv:sfSS7mr9qP9bllvXHFuhHt4VsoeyDdWjCobPbeqA8kg=,tag:DmnKJyUKMCFFG/Jwb7YxKg==,type:str]
    password: ENC[AES256_GCM,data:BijIk1vkCt0RpFTeqSoCqlIdrX6zElJJc7uArXPO9uY=,iv:0pIhd0NmW5FgTWLffPDqFrvbPTbgVlvYRcr7H9NGtX8=,tag:ezdvKbsI7Ol2owlWfra4KQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCT1Q0eTRxN0t4a3FndVFS
            SzZKOWFWcVRDQU1WMzNJOXYxdmRObG5xQUU0CmprQ3FsQ3RzREQ1aTlxWFlac3RY
            VDFGdGpHZDFIZ1czMmZRUVAvTnRkTmcKLS0tIGsxbElvemF4OTVXMk5pZU44Zlpt
            UkVuS2FWYXlZbDVWQU9DYzA5R1RycFkKpR6FO8lon1BC9z1kmW3EaiWWrvT64WZv
            kgJ1cCXJdOBTyTUmYGTYbgZi8pl/KRVZF7sC0KOjgu2cQerupsR1VQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T11:18:34Z"
    mac: ENC[AES256_GCM,data:N5UcPoDbSkNXFT9P+E1kqiy6usgnWKGQkvCMWMt05XmuzeY8yi3kySpWMED3+Ecvq751FkBkP0lP1oPFiVpVnCDCzduDTUzHLrm4jxRd5I2HXLcGuSGfHCyXF3M2HzWR/bsULLMzXamGsqjgXv3zsoPcWjERrJrGr7QdRcD67ds=,iv:9qpngqCswJ5ooSjrj2L+OdbP6KOMC6nd1KX/5TRQUfs=,tag:SWtz+B+e0RrPVaGh/cr92A==,type:str]
    version: 3.13.3
