apiVersion: v1
kind: Secret
metadata:
    name: core-db
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hidDfg==,iv:0TVe/Ie9NJLvEXdJEQeCCjwoaBHsFHYwIyP0KWz05/8=,tag:HyE7IC9/13O0zVQeHDAbZg==,type:str]
    password: ENC[AES256_GCM,data:ZvlfuEItLQK9Zq3MR4ZlaQfZXc/BW6Ku+cOtMnKv9Pc=,iv:Yr/XjoKzqeKEQB1P0Cd4twQ0cd6BijVxFvaT+A9WBv0=,tag:cosPvCjMGMpXPsLaIPk1Ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR2h1bktDSE9MZjMvanpX
            ZWR4SFI5ZFlTK0JndDdKUDYrWFg5RlZXMWpNClJCWjRNSFpuL0ZzeUFSSXduczYr
            UkR5QXQvV21FNU5Oekd6bFlsSUJpR2sKLS0tIGV1RHNQNjRqQ1M1WVg3TDBna2xR
            RiszWmc2emV6NHVGTUllV1ZDeElCalkKhQa9ksfxQsU00s75gyitK+zdUCKyVecp
            +dClikPFBNxubVcYqksJAaWgLwDKUn2Cc1h8Hhpi6ndGYX/b+JGChg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T12:26:34Z"
    mac: ENC[AES256_GCM,data:P21eZyEswFkpDiClKLDyUPCo6X98o8cYSUqF2EQS8saxH8gGYQ1PDxq6ZTk/+QMzvvsAYtYY1V0pDG6Etiv/H8NV3tZCbVG7qi8joC3G4bLKGEXKBk5gczCXUyx3dM/KBspQZZYZRsjrXMU7ER1VQbouE+Ol0Ay7pvmlRLwYd64=,iv:22dQRqlCQQWS3cxuG47kByl+neaVV4FJ7CZQf6Ep6r8=,tag:9wDO1VS4Td9lyx9FaNcRuQ==,type:str]
    version: 3.13.3
