apiVersion: v1
kind: Secret
metadata:
    name: core-db
    namespace: apps
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:MN2uHQ==,iv:sfSS7mr9qP9bllvXHFuhHt4VsoeyDdWjCobPbeqA8kg=,tag:DmnKJyUKMCFFG/Jwb7YxKg==,type:str]
    password: ENC[AES256_GCM,data:BijIk1vkCt0RpFTeqSoCqlIdrX6zElJJc7uArXPO9uY=,iv:0pIhd0NmW5FgTWLffPDqFrvbPTbgVlvYRcr7H9NGtX8=,tag:ezdvKbsI7Ol2owlWfra4KQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQXhnTlVzeXo1SFovTC9v
            NnRHOE9IeWJEanhhMDNBamJKQXA1S01NdkM4CnRTS01MOGNhYVpPVFpSMzROMDB3
            SFd6RkpyaEgxM3FDYklILzhIb3BQT00KLS0tIFIxdDNqTWJBblFzOFR2UExVV3FO
            ZG1GRTBucnp1N2tLREhkVFdFVS9aR00KOQhrhNLMOSq3KMMtumKxsb6w4aMcMTC6
            /J0YXlOl8UI9rskQE+EbY/BPqpm6LuTScswmubbgRecV+aQTT7ZV+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0bEgyS3RHOWNYN0tPVGk1
            OC8xR05ObnJNZ2F5ZW9XN29SUkNkMlk1U21BCjBLSWV5eHhYY0xqZ09qQWFHdWVS
            SjJPNDlEamFQbGNhaCtXYXpxR3JJNUEKLS0tIFZFaE9xMXhjdEMzKytRZ0xUSkYx
            U1lnYVRWaTRGUHBQYkRiZ0F2UFNpMW8KnoKZVvxJ+uRIzYRFeCB0SmjkzA++sLiU
            RcaPVJEALDi4rL/eON3TaKQm6RX0hz/hEhrBuhkNjP3KG15wxYxUGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T11:18:34Z"
    mac: ENC[AES256_GCM,data:N5UcPoDbSkNXFT9P+E1kqiy6usgnWKGQkvCMWMt05XmuzeY8yi3kySpWMED3+Ecvq751FkBkP0lP1oPFiVpVnCDCzduDTUzHLrm4jxRd5I2HXLcGuSGfHCyXF3M2HzWR/bsULLMzXamGsqjgXv3zsoPcWjERrJrGr7QdRcD67ds=,iv:9qpngqCswJ5ooSjrj2L+OdbP6KOMC6nd1KX/5TRQUfs=,tag:SWtz+B+e0RrPVaGh/cr92A==,type:str]
    version: 3.13.3
