apiVersion: v1
kind: Secret
metadata:
    name: core-db
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hidDfg==,iv:0TVe/Ie9NJLvEXdJEQeCCjwoaBHsFHYwIyP0KWz05/8=,tag:HyE7IC9/13O0zVQeHDAbZg==,type:str]
    password: ENC[AES256_GCM,data:ZvlfuEItLQK9Zq3MR4ZlaQfZXc/BW6Ku+cOtMnKv9Pc=,iv:Yr/XjoKzqeKEQB1P0Cd4twQ0cd6BijVxFvaT+A9WBv0=,tag:cosPvCjMGMpXPsLaIPk1Ow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpZ0F3UDlxU0NTKzI0RFJu
            VGxlbEFtMXBBdjFBQ0lDVnljOG1NVEhweFEwCk54bW1UaFZmYmVnTWIyTVlpTTh3
            OGhqUk5Qdjd0VmJoaFZNMktMWDF4SmsKLS0tIFVNRUtIMVVJZVhVSkZrYVRnU3RM
            UVVXWHdRSUhsSitZYSsxNGlCN2lBb0UKW+mIc/6Uql5BR886I+xBFMqTpZNqrq/t
            PXHNonR7NUPyfJo4SVVkZGloS0EmDCDgtf0GxfX4j4bR0lAaRTIn3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweU9sU2I5V0tNWWQ4RGVn
            SzlhYkF2eFJOYUVmcFJVdmg5Y0tHR05KdGg0Cmc1VnBYLzRmOTN3RGJFUXVRcTcv
            dm0yeHl0RHRkZ0kyenEvWk5aQ00xZkUKLS0tIDhkNXprSnFid0xZa1lNOFpqQkxl
            MTRxM2I0V1BDaWM4QVlET2xVb0pLNjAKNiJ3fWgxVSgAYD+qr6uZ+ePYKhpMMZvV
            ZaoLXkJhJRJAaEaFGFs5yVhZLZV8oDGIj9bNcoCDFLstBA/hF08stg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T12:26:34Z"
    mac: ENC[AES256_GCM,data:P21eZyEswFkpDiClKLDyUPCo6X98o8cYSUqF2EQS8saxH8gGYQ1PDxq6ZTk/+QMzvvsAYtYY1V0pDG6Etiv/H8NV3tZCbVG7qi8joC3G4bLKGEXKBk5gczCXUyx3dM/KBspQZZYZRsjrXMU7ER1VQbouE+Ol0Ay7pvmlRLwYd64=,iv:22dQRqlCQQWS3cxuG47kByl+neaVV4FJ7CZQf6Ep6r8=,tag:9wDO1VS4Td9lyx9FaNcRuQ==,type:str]
    version: 3.13.3
