apiVersion: v1
kind: Secret
metadata:
    name: gateway-oidc
    namespace: apps
type: Opaque
stringData:
    GATEWAY_CLIENT_SECRET: ENC[AES256_GCM,data:OQMxnHjLV3VaasaUFZZHtW9Ouwou/pf3gwaS1L2hnO4=,iv:uQVO2nvUnxdPeJ+EUU8iCxKi172aWzIGsAOf3tI4P1A=,tag:W0s40ZD/MFssiRh62+U9uA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNnpBbGpQenBuN2VNMEJX
            blcyNy84VmRwb3E5dEU2dWpHaTNKWURRUmcwCkpIMkpSdUVVMW5MSGFDc1VnM0No
            cERQTUdIemhyQkJDdkdrQlRNNHRWWTQKLS0tIHRhNFBQQ2lWVDRxeGttR09vcTRO
            d2hvTEFFUG1GVERpRXF5UGhBNlA5L1EKEitUJs9s0CIycbd1O+xCkxSz04r0i57D
            /ACXypmU87FNCQtBzMfvP3PEYrbCduMyJo0mldaD8qfSN0cbrYiNnA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbmNHME9zRThXTzVnVlRu
            R01RWEVrMFRoWHBnaFpBeGxiUHhKNnh4UDBNCm5ZdjRpanZGQjF6ajlwTlAxTnFG
            UGkrK3BJdE5lMWlCVGVISUdnVVo5TGsKLS0tIGc3TThjNTYzRmpvWGhDcHVnVUd5
            VVhrQUsxZE4vNWVXVWRzaHJSVHptTWcK/bum4G/10wQxJ4cK53TxciNE+bjBQ8xj
            utFmL9ih708y6KEi7ENnuLYFSNF714twlfGin0nmZ0lsle9EK2evTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T11:18:49Z"
    mac: ENC[AES256_GCM,data:miDGGOxgP7431CooDGROqHl6TeTA7iQNougvkAhMGpGY6F0XXsvMyGYN2v6LyoiPRjI2d0XxJIBaBTejsQUKm4iTuoI+QdsNUJ2Ku1Qar52VWhzp+AYSHgfOMcKLpfAY9i0/cBgss5b5fgKe0ED2xCs8OK62ruoY4z4OPjHhRE0=,iv:l5VDJR3zbu3Nm0Ne8Yr6SRGk7REKrZZ6N6DtNT+ZwsY=,tag:2qydZA8s4S2exvlEfvAudw==,type:str]
    version: 3.13.3
