apiVersion: v1
kind: Secret
metadata:
    name: gateway-oidc
    namespace: apps
type: Opaque
stringData:
    GATEWAY_CLIENT_SECRET: ENC[AES256_GCM,data:OQMxnHjLV3VaasaUFZZHtW9Ouwou/pf3gwaS1L2hnO4=,iv:uQVO2nvUnxdPeJ+EUU8iCxKi172aWzIGsAOf3tI4P1A=,tag:W0s40ZD/MFssiRh62+U9uA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VmhSbHA4VGJHUWx2S2FU
            dHRiZndhdGNpV2ZPcHJPMzNRQTJpYklPWDBjClFRNjlpN051Skk3NE5uczk1UFky
            VWMvK0ZZeGJVNDhLdDZQUmVlaVIyeDAKLS0tIER5WHNVbVczZ1VncFlkbmFvZGZ1
            TG16bjJmeEh5cm9Yd3RIeE1BcS9zSXcKDymXoeR0tkA+ftGfs65py69JMnVxLJTf
            XPqAl80BBfdvsu5Z7zznr/3hbhtXOyEtMbWUbXon9cfc5FNoxzomdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-21T11:18:49Z"
    mac: ENC[AES256_GCM,data:miDGGOxgP7431CooDGROqHl6TeTA7iQNougvkAhMGpGY6F0XXsvMyGYN2v6LyoiPRjI2d0XxJIBaBTejsQUKm4iTuoI+QdsNUJ2Ku1Qar52VWhzp+AYSHgfOMcKLpfAY9i0/cBgss5b5fgKe0ED2xCs8OK62ruoY4z4OPjHhRE0=,iv:l5VDJR3zbu3Nm0Ne8Yr6SRGk7REKrZZ6N6DtNT+ZwsY=,tag:2qydZA8s4S2exvlEfvAudw==,type:str]
    version: 3.13.3
