apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:vlyV6S8=,iv:Rth4F3LGzVbkFWU1S61YrZ4enokriM9F/+espX9kC+0=,tag:O0NfIc+YoTw782fWvxiVOQ==,type:str]
    admin-password: ENC[AES256_GCM,data:OB1APalMwQaA09t/W+lp9ocQQvKO0xDOe1+z8g==,iv:yzeoxMFppGodNdpFV8kgg1Ext3Beba7q0osTLduIZN0=,tag:JTrKdWoCmTs+Ma4ul5gY/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTE9Cb05CbU5LZDEzUW9Z
            WkV0U2ZTMjk0WjRpTVQxWHlQU1ArU1E1dUJVCkl5K1VlTmN4Y3FCb09wc2tYaTVO
            ak1YRE00WFpMY21ycnBxYzRXcXl4UkUKLS0tIFZKd3JiNGJwMDNFZTFCaEJSd3c3
            UUZTaEY5eXBuMjdyZ1hJYmI1ODVEZzQK9PMA4vpKmt5VbVW1PT4s7rzrJj0bRk7J
            084GGaLCj3M2MUDHG0zjkHAnDphUjQ1Ms2GM17itswtgfJV3ohiwvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T22:28:11Z"
    mac: ENC[AES256_GCM,data:ax/DIVkWWXPwZR0VXyAHSKSnfIHfe5pavbJoTvpbAj+ntkGs6E0UKBXBlqA9PpSP51wlI4KZG+QanoHeWvRqKBc+eZfOalPVSVohbUIhWyoWqDMDYwTC+qjNTRHli8m9BXYMeSZBGCXdEHWBc9hZ7ag3+c0wmSOl0L0K6/yDFhA=,iv:Y4VFS1Exjq7xIauvtCQXqkjVcjD14j8Pou5AbODAPAk=,tag:TIKvrwKF92OZpBponEwrXA==,type:str]
    version: 3.13.3
