apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:vlyV6S8=,iv:Rth4F3LGzVbkFWU1S61YrZ4enokriM9F/+espX9kC+0=,tag:O0NfIc+YoTw782fWvxiVOQ==,type:str]
    admin-password: ENC[AES256_GCM,data:OB1APalMwQaA09t/W+lp9ocQQvKO0xDOe1+z8g==,iv:yzeoxMFppGodNdpFV8kgg1Ext3Beba7q0osTLduIZN0=,tag:JTrKdWoCmTs+Ma4ul5gY/A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWjZRTllMdittQWJlalRu
            TFVBemNCcFZKcTdaaW9xalI1YXJlbVUxZmpRCnFxSnNiOTkrQXJkTlFKbm1jOXlV
            UytjVXFwZTlUQlRYcFBUUGFpbFh1TnMKLS0tIFh1ZXBHb0krZXRnN3JwWDFNTThZ
            UElZMmxpbmpFUFFSMzY5Q3BMUnZEMjQKDP1eGucrxaJhQrTh+h8qUiFm5PHnaZc0
            H3/2DcwYdlRG4A4qByN+7vKVnB96+vqmQar1ULZFgd6T3Udl9qiRiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSTZnWVczSkI5TDRsY2Np
            Vi9vcEJiYzM0SXNFMzRxR0M5Y2lyN2dBTFhrCjQzZmVreXI3SEF6UHJyRkljYkpk
            UFRwaE9tM1RtN0NRZ0xhRjFEMmJMVGMKLS0tIDFSa2VrVTYrY01qMlVkNnFTSHlp
            ZzhqVUhGaUlVOGdEd2pDaXY1d3F0UDgK7n8p/g2iyEn++GQoX9b8X9Cu9LEseOr5
            8jP10bcU+DL2aVLt+fe/+PqPqR/luzLqpiiLHbcSA1JXtEkieD9uUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T22:28:11Z"
    mac: ENC[AES256_GCM,data:ax/DIVkWWXPwZR0VXyAHSKSnfIHfe5pavbJoTvpbAj+ntkGs6E0UKBXBlqA9PpSP51wlI4KZG+QanoHeWvRqKBc+eZfOalPVSVohbUIhWyoWqDMDYwTC+qjNTRHli8m9BXYMeSZBGCXdEHWBc9hZ7ag3+c0wmSOl0L0K6/yDFhA=,iv:Y4VFS1Exjq7xIauvtCQXqkjVcjD14j8Pou5AbODAPAk=,tag:TIKvrwKF92OZpBponEwrXA==,type:str]
    version: 3.13.3
