apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: database
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:6OJsRwwF1wc=,iv:wY1uCxxa3GPLOvB9lp3Og9KzOWMo33wNH+RpK4pz/7M=,tag:dHJyPsjukvw8ZQDwGiA1IQ==,type:str]
    password: ENC[AES256_GCM,data:0+Zh/a4rR5hxwCuvejrAQctSg5NFPqy05BmJZak4+Cw=,iv:VQq7yW8KVQHFJS7T3RfPmLfyHP/5KmGiSUArbgORpkI=,tag:iOn8IFL2emDkzwGvF/1aiw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPaWlLblRDNW1YaDZvVHpW
            M1pxYkt1dEVpWCt6OUtWclh3ZGE0a1dPRzE4CkFrNC84UzFINUtNRG8rTkJweklB
            T3RCTE0zdXFmWm10eExsN2E0aVBEOVUKLS0tIGtKZk1kRVFCRll5QzF0WCtTUThh
            Vm11dzFwWVo1QWFRaERJNEwycEYxdzQK1q4ErR934XtSf0Bbl2HNh0Ntpo60fxJn
            3toEJs2QQID1AKNqmfbptyYfe78rRsFLeAIIypaWbKXjA3/jZ+louw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS2dscms1VDFjMWpNaWtP
            L2pKS2RmdFM1dGRwZXNmUDZ0YzRocWlhR1JJCjFqa1dDUTl5aTN3VWxrMCtqdkdZ
            bU5ZOUdVSWJPaVdZbktFM1dCbFlzZGsKLS0tIEZWbVRkZ0M5SXpkY0tsTlBUNU81
            UGl5b1dzR3VhWjdpaExxbVhSeWxubVEKbDduzN73oASF0VDuseexaXTNgw0qxp0D
            1Lo0xEci1kEl385Bg0hWBA84OO/+Puej4sow0V1iA/WnvKoQ+mNitA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:20:56Z"
    mac: ENC[AES256_GCM,data:Wjd7LPikDmsf8v2K8S38gs9JnVCMblDOnRat7oaztJkuD3cN9tn3cpRgBRiBG6MYrf5exEL7uFnYqE9XOGnPjzvk/wqPdQrit9in2Mx8YpR601skO+KATNxahvhGWPEre2TSuJY48AjBF4dCAv9Vhrpetpq5z2nFufH9Ae01vKk=,iv:FInu18zi/JhQFqgwe5QGc/17N5fLgHMSehzwsT12BhE=,tag:M/EpVGbnjUPxc7ALV/TkNw==,type:str]
    version: 3.13.3
