apiVersion: v1
kind: Secret
metadata:
    name: keycloak-clients
    namespace: keycloak
type: Opaque
stringData:
    GATEWAY_CLIENT_SECRET: ENC[AES256_GCM,data:OQMxnHjLV3VaasaUFZZHtW9Ouwou/pf3gwaS1L2hnO4=,iv:uQVO2nvUnxdPeJ+EUU8iCxKi172aWzIGsAOf3tI4P1A=,tag:W0s40ZD/MFssiRh62+U9uA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUk9HNW1lamhWVVBmMVpT
            VWZwS0ZNZFNNMTROT2hLN2VxNEg4Q1NWS0hvCkRTUEc2aUVuTVl0a1NvODR2bWs0
            VjB4NnpSWVd2eTM0K3lmMHpLeEJnWkkKLS0tIHB3RllSZzhwc3FuQ1FaRDJVMk93
            eUp5eUdiUDF3ekZ1RGM3WnhHMkd2Z0UKhNmSxXV/wD6m3FGE5JyT6UtZzADgeU/i
            R8dXAzjLtCU2G0CMkBuU3PWnFrOorWD+AJyJHqbJ4orQ65v2ZjigNg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGQUUybGFVTDZ3Sjgza0tS
            WkROa215aHYzSnJ2ZDU2MFo3Y0dmR2tFclI0CjkxVWZWQW5kaUlxc2N0MzR3MGgv
            RGltRTRxQjVaNGhGZ3ZZZDZoT3hwRmMKLS0tIGN3ZUlaQUlkOU9yL3lPbzFhYnZI
            d3NmbVd3OWY0UUE4UHUyS1h5cnpVUDgKA5BZVzhPT8w8ZS2qZN5NCZdxfA2jdTeF
            0LoOdkaTvmm8FpfIbI1DMMFV7s/+zQ+jii2kuJ0Ka1BZ0TDZTCgnfw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:23:23Z"
    mac: ENC[AES256_GCM,data:M53yTRARp3mUO8dGyh0BO9Nt6YPFGV6456dPVtCL5wGqyrvrYE673dML1qfUmTzcF97Lw1pvf22NNjhuFSfsQHt61oGqNL5dIgSRJNLE5O9u1wO2q1oKaCB7RenMg4RLqGpYlFd5fWNswpiXHJ92x2LYZKY9RWZ2T2I5tr1c2JI=,iv:ghEl3SUAEkt/h6B1gursvUuLRrsQ9vquUczR+qTd/0I=,tag:zlf8xecTvTcB+AgN4WpO/w==,type:str]
    version: 3.13.3
