apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4dKk6uaXI6A=,iv:NRzxfI522ixnE9ijSmJOyfsirIafPzydyoIIKUWJ7MU=,tag:zlMhX73gEMJ1bjZfgQhBaA==,type:str]
    password: ENC[AES256_GCM,data:B0BppMHGQXaIUnotnUBkUxij4AGwQc2+jRUnXPZlBlE=,iv:J8JegffAn1V50v9VmIJv5pRFixMbzCXQzwjkAwAtBaQ=,tag:zhq4HFbawnOsBFOK8GqwVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QytoUmgvdEVvU1BXQytD
            RmU2S3J4UDVmODJFazBKWTNVcjFIemUrc0NrCkRxdjUxNVc5YUFDT0Ewb0dVMzFo
            a2xLLzJIS3I2M3JFS3doQjlXdmhFcnMKLS0tIHlXbGhMUk96b21KYjZSZUxmV20z
            TFhsejBSajVkVTRHZ0JpWHRwejJrWUUKgvb/YDmawthjKyhmgzz+V+NIbRtF5YJK
            0qx8Dgq/G4H1IV3m10mVSJOapxvUCWE50Gm/NRkjipdy9z7v68do9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:20:56Z"
    mac: ENC[AES256_GCM,data:hGVMH+NRWgZFkEPDBylTQE8bk0feY7/Hy1StEh3tfb4/gaJ1PxhhYsbRKtbvGKObUNNJFCdJ1fbByxYgzutljrwQyw8COcEsvzisyU73liwnv2Kpj1Q1iPi9R5/f6LAUBfHHEg7v4wrgYzFcpyK+kUGE+HUuGD04MRwNQENWHXY=,iv:Mmc2gLi5OEt0rYZ0q7dQeRBnVOT16hNtJuwr0aWAYHA=,tag:QiPQHTyu1vGy4tfRaPTCVQ==,type:str]
    version: 3.13.3
