apiVersion: v1
kind: Secret
metadata:
    name: keycloak-bootstrap-admin
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2c7b+Fg=,iv:IdbHLn2fJJhFuQN+iKjrIKm2On40ODrOBRwy3OBSNbo=,tag:/LXHnXyw2rqXu9Amt3f2bA==,type:str]
    password: ENC[AES256_GCM,data:MwwS8bVUvqtYJQL5/V9QaJjzCAnT909FiYKv2GQtxds=,iv:xsa3jcLZJd3HUotFAso/FGnBkk9LAhXpj6j10UET+Gs=,tag:yueL66taIqg759iMKP48ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSlJmRnZKaWFqKzExOWhm
            NDdUZ1E1dklMOHRvOWxkWWtuWDducVpvQVVzClZ0cTMxWDFIMkZ6bHQ1ckl3Unhp
            N2xVd25wcno3dUZHaG04amVteEJHdmMKLS0tIHlMc0tqZ1NDTjJPN1N6RDRGditG
            MmljYjYxUE5IVTdEMkVYaG9NSmFrNk0KS4Md4l8R9bjl72IEViSxMncQBDh6G8of
            BxytC2qf9JyQ/7g7swGHfUT/e4VAOSpwDtnWHiYdhyhvWFmwclQJUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OTlodTlVckdGVEpieFRU
            Y0IrSjM2bnVWNFA0TnZ6aU9Pa0JMTGU3T2pjCkg4N1ZueTFJQUVPekFTV3lMa0tY
            bVY5eW93Y0E1eW9hZjRkT1JLUEdnOUkKLS0tIGlYSkhlUnZiQVNEQ0U4bEZXaXRl
            R3BkWWFNcUlmTFB5cmgzUnA4am9wTVUKcE5TmQuJMAL7NZmJmysDEcxACLjVCQK5
            +A6L1sDZh3e9lfrvilgLqcJGwgB8SsoaybQcwegtr3xjM+WCDmWIiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T22:00:41Z"
    mac: ENC[AES256_GCM,data:oG8jpkdlzlnYURQ1WE2NIF4rfXhpI7X8srKzEJx0ne+kC3Bu++1v+eExyRnHpR/7biJH8Kzh9p0BBpXYUzvcu8+JSWvwvGzcDlzJ7xEHFBZrP+gjvbDsZsEjC/07WIWQZW32SKfgUbAAPDeCpcNJ5t7EJWZ5U1DaHCNjB6TItUY=,iv:DXLSpErqtSpaR3bZHFWqUgBtENnvr9nRfRhc6gVcCgk=,tag:1mY6fpV4bGcW9+E3uD7pRQ==,type:str]
    version: 3.13.3
