apiVersion: v1
kind: Secret
metadata:
    name: keycloak-db
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:4dKk6uaXI6A=,iv:NRzxfI522ixnE9ijSmJOyfsirIafPzydyoIIKUWJ7MU=,tag:zlMhX73gEMJ1bjZfgQhBaA==,type:str]
    password: ENC[AES256_GCM,data:B0BppMHGQXaIUnotnUBkUxij4AGwQc2+jRUnXPZlBlE=,iv:J8JegffAn1V50v9VmIJv5pRFixMbzCXQzwjkAwAtBaQ=,tag:zhq4HFbawnOsBFOK8GqwVw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRXUvZldQTDNBZTNyWk5T
            QXp0NTNqUTI5T3NmeXpIUTdrOWoxUnV4SGw0CklVZmptSE5BaU1MZHQ0QnN3ZDBr
            anNtSjlnWitMZDEwV3FvRXE5QjUzVGcKLS0tIFZYc01DNVh3cjNGcE55dmNNK0JU
            eW5vaEVWZUx5V2kwTDZLNkV4cldGb0UKJrbf3TT11RVOYE7/xDYU0fACuQhxPCSU
            emYMftYAD95Km7j5cPhR/Vwgf0uyIMKgpfOF2EF7VRRQbygvYJxblQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjL1JIUjRCTm5ucjk4THpy
            aC8xVE1CSnZMMDdNWWpldjFRTnF4d2pvQmpRCmN4aGtmcjJuQXRLb05vNGZ4eTcw
            d2RhdHRrc2tWKysvUStqMU5JOEd4bncKLS0tIEZVTk40ay9qZFJpSWx5NGNaYmZH
            VVhiQStQa0UzYXpxSzVqN3V4b1JYdGsKVGjVAe5bA8x70ipvc05qi55v349zkb0r
            rlZ/za6VokvsB7Mzd1Oca4ZgbtDc8i09vTGysuRC3mCoJ6Id2aVXvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:20:56Z"
    mac: ENC[AES256_GCM,data:hGVMH+NRWgZFkEPDBylTQE8bk0feY7/Hy1StEh3tfb4/gaJ1PxhhYsbRKtbvGKObUNNJFCdJ1fbByxYgzutljrwQyw8COcEsvzisyU73liwnv2Kpj1Q1iPi9R5/f6LAUBfHHEg7v4wrgYzFcpyK+kUGE+HUuGD04MRwNQENWHXY=,iv:Mmc2gLi5OEt0rYZ0q7dQeRBnVOT16hNtJuwr0aWAYHA=,tag:QiPQHTyu1vGy4tfRaPTCVQ==,type:str]
    version: 3.13.3
