apiVersion: v1
kind: Secret
metadata:
    name: keycloak-clients
    namespace: keycloak
type: Opaque
stringData:
    SVC_CORE_CLIENT_SECRET: ENC[AES256_GCM,data:TXLIYXDltMAykGonDehxnK1Npx3gAgxQsILNFoxwOOk=,iv:3u3tg72F0tnJnhI0gAmzguBG2ov64n31mnPOg2pT6fQ=,tag:ipH3+sGsrg0/k+6WfbfEfA==,type:str]
    GATEWAY_CLIENT_SECRET: ENC[AES256_GCM,data:CJnJaz6dav2pumsoK7OVsPKZR3hWnBQB1nzh4pX60vQ=,iv:ixe/6lBKYJqrOQ5d5wggvUbj7a56jcF88H4dFZbIXZM=,tag:8foDce4eZptpMdIdqIQKRA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaTREZ0l2UDd2L3kwakRX
            bGFmU0NORDQzcjI3K0psVWZRVFpNYlBiZjJzCjdyQVA1YTdTS21XampRK0RTNElQ
            dFFJZHpQdDRyZGVwYVJXOW9BTDFINkUKLS0tIDdWcG1DTVM3d0l0WHM2TFNRK1ln
            SzZPQ1Bia2hDcWpjbGxXL2JPL1ByejQKV8tec5yEWkhVS2pWvulEa2f540ogDv1Y
            HzsSzBYIkzEF6YnJlUv/ThGOEbtmQIlpewgjgEhVAZnq/Vk7R84MZw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aEhNbjVrS294YmN1UHkv
            TW8xQk5DaEEzc0N4aE9QekFlNHJIS3dMYlR3CmYwaWJvNjNPQVNqQ1VocDlWell5
            R1pZK0VlZEwxbzE1MUNVVThvME5mMTQKLS0tIEVDczFvR20ybTZ3c2VjNUJRTWdC
            VFdHTmllb0R4SGVLU25ReVlFQlFGTnMK7FMfoOaPReHzoWL9t1SgoMg+Ta+rJNs9
            ZlUBy6uceEAh4iH7qVmHEwpHFhCqfzpIjp39u4KfW7jz8aXsU7dCtw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T18:35:58Z"
    mac: ENC[AES256_GCM,data:Of1ujxveAs/yxudRWBXyS3muylfus0+FAiZ9Hftd3P8iqEev82B39Q2bWyhiVQfop75tBa4FRXexYhIBc8FKZX0Kk53YIK28+LBDvLW/iHTQvwBw5gu7q6mp9RYBn4MjDTZPeXHAuXNDXSlm3P28SiUQfuOAvzqHUAkGS+TFRCU=,iv:gAh0pKif1k9SEJkkvM+poa6mDBjarp56uhapb4pUjCw=,tag:sLDUCaGP+kDE0SeE46KCuQ==,type:str]
    version: 3.13.3
