apiVersion: v1
kind: Secret
metadata:
    name: keycloak-bootstrap-admin
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:2c7b+Fg=,iv:IdbHLn2fJJhFuQN+iKjrIKm2On40ODrOBRwy3OBSNbo=,tag:/LXHnXyw2rqXu9Amt3f2bA==,type:str]
    password: ENC[AES256_GCM,data:MwwS8bVUvqtYJQL5/V9QaJjzCAnT909FiYKv2GQtxds=,iv:xsa3jcLZJd3HUotFAso/FGnBkk9LAhXpj6j10UET+Gs=,tag:yueL66taIqg759iMKP48ag==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkN1Ira0ZveXB1a28yMVVn
            Z2R0OEdIRDZBVWtQLy9DUFVsNlo1cWN3QW5rCkcrOWFOYzdGeVdENm01a0U0N1M0
            a09VQ09acTNPMENxM0hBOUc5eTgvUlEKLS0tIHpQd3B4QTNQdzl4QkVhaTVRd1Qw
            UEFUWXVjbUwrWURqSU1pcGNETUw5amcK/3NIJmnEowPBYqhRdy93TF+gtMa7kVbZ
            4taruGj6o0/9p8NCQU4OtuvrjzkzqIYeIhPAWXNSNEwZq86iX7/REg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T22:00:41Z"
    mac: ENC[AES256_GCM,data:oG8jpkdlzlnYURQ1WE2NIF4rfXhpI7X8srKzEJx0ne+kC3Bu++1v+eExyRnHpR/7biJH8Kzh9p0BBpXYUzvcu8+JSWvwvGzcDlzJ7xEHFBZrP+gjvbDsZsEjC/07WIWQZW32SKfgUbAAPDeCpcNJ5t7EJWZ5U1DaHCNjB6TItUY=,iv:DXLSpErqtSpaR3bZHFWqUgBtENnvr9nRfRhc6gVcCgk=,tag:1mY6fpV4bGcW9+E3uD7pRQ==,type:str]
    version: 3.13.3
