apiVersion: v1
kind: Secret
metadata:
    name: keycloak-initial-admin
    namespace: keycloak
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:6cgeHqY=,iv:ccl+4RPcNJhYbv18+xQWmGaRSea03Jon5XguLXgI9qs=,tag:Nfi0JCzmmk+NNXa3auO9HQ==,type:str]
    password: ENC[AES256_GCM,data:fcybPhY68nqBFD0B3GazzdXbcyPRqWBI2Xj3FlelhJA=,iv:XU02n3Q6o1vVW+FDYfbOtSk39jMeQ9XNPFYvUqRCMUE=,tag:o5jhyTw7/e+TimE6q4x7lQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRTRhUUVSclJUQkFsNmN5
            YldyNnlNK3AyalV6SHRCWVh1QUZiMGhya1FZClQ0TmVkTXEyK3NldzAxSFVKdlNh
            Q3Avb1QzUUwvbkozaHB6a1hXd0lvZ2MKLS0tIGRBTmdlNkQ2Uy9GRE1OUDhHc0Rs
            L1BXUVRkUU9ZSWtWM25OdlFSekwzdWcKE1SunnBo4WgYuPlz8zGZSRk2Ncb9NcN0
            jUdNamExftLCoDjSnZhcxZT/CAyyyw8Bd3Jkk7nlgTyoEgSEPdAW1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T21:20:56Z"
    mac: ENC[AES256_GCM,data:sWffkQgBwgoh1r6PKAPoRj+ajvN4S8JJF2oaR3A05RMQFwh2NVHA3X1Dp2w5aiEoIpxiotq4OurNisS2oY2DXlJLeMh727rwyQYs+KtQKuJwCYFCXq4R5Tqv6YAbSPAr6yc6CYuduYPvxjzdDBh9UE2quecFNlIGF+8WJoIY0XE=,iv:UQ/6S4jaxrLvUh/XNQqYXp+Dn27LFZ/x0ZRQpcdT15w=,tag:qhO6OnuCfnl+7BsIWZkffg==,type:str]
    version: 3.13.3
