apiVersion: v1
kind: Secret
metadata:
    name: loki-s3
    namespace: observability
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6CX+csHi5JmgXkm/WSE+/79NKCY=,iv:GNoLQCVhHvr0p3sYMvnvA9rC1ynYHaRdYvFb5g6KUsE=,tag:iXmIACdEbIhYX90opa5Piw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yYXq8EVebUXD7t21lpxxIKn3YcXO0nWWBFTp2cKhLxp/ICUQw9rWxA==,iv:5AQWAZiUijtYgokCPwF0dhGP1GoP9vHvvsXs59wH/K4=,tag:hdU4ZjXgman+Lx5txjL1Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBja1IwMHhmcURHb0tDeFJ5
            NjNtTVcreTdvZTloQ1RVYzZYclkyb0hTa2hVCjM1bFFjTDZFTE9pSms4Z0NnZmRJ
            c2cwUE95eXBsTVp4N2FrbkpsRndYZVUKLS0tIFJBdi9hSjZCWHlpMmVaaGZvNkxI
            K0Q2aFh6NmxIWG1vN2orUG1wRUJlNmcKp93G7qAGVhEvgVruxZMwCVhqFi8mvvbE
            Yx/VA8lgEAajeTIFXVRfxANE1vb+/NiNS0Trb3JhsYn5w59dLrf8tQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMGVGQVc4QlRGbnZUSHFl
            Q3JUa2xEMVAvQlhjelE0c3pOOXFnclpqUmtFCjdKM1VLejdzT1VFMEEzU0NVWXEy
            b0Z2NE4xdklqWEE1RU9tTHFxWFlyUkEKLS0tIGI4VjRvQzNSZUNRSlRNcFhpNUg3
            K2R2ZzlVSldtU3l3c3gya3R6VnlHd1UKszQfStP6ma3kmai0kDqeKlBKDBsCqA88
            BwhE4Q3HDWEwXCUTKWq9Qsy9XJOkfuy2W+q9w/zSz6sZuN8C7eCTdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T23:49:30Z"
    mac: ENC[AES256_GCM,data:OvaFmJ/vwHUA0JP+YYbGk6ppD9VtGMYWr3xc9iYSAjb4tQxF4TfpCQM0mnegNmSMujB/AmiWZypgAPAEAJVvUX2suPO2+GL2AkpT7VpOBr1HeFWPx4XFhWzmBEX3R+fm1vhdNPp+/jc9iJoSwZKInZYUiItEGoz2VSKZ/W7hDX0=,iv:gCRfIhnHhaYaXdDbFwsY+umsh6WOjvuBh+m3M8SSCwk=,tag:fewEnkFQP0aRK3c3eLpu4Q==,type:str]
    version: 3.13.3
