apiVersion: v1
kind: Secret
metadata:
    name: loki-s3
    namespace: observability
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:6CX+csHi5JmgXkm/WSE+/79NKCY=,iv:GNoLQCVhHvr0p3sYMvnvA9rC1ynYHaRdYvFb5g6KUsE=,tag:iXmIACdEbIhYX90opa5Piw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:yYXq8EVebUXD7t21lpxxIKn3YcXO0nWWBFTp2cKhLxp/ICUQw9rWxA==,iv:5AQWAZiUijtYgokCPwF0dhGP1GoP9vHvvsXs59wH/K4=,tag:hdU4ZjXgman+Lx5txjL1Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTjc1S0lzRmlyay9mZHFF
            eTZtMUNMWVJkS2Fna3lYTjNkTGdTbTZrMVEwCnRZQjRVRzhOTytFZkNQcTRDRXY0
            TWUvbHBrTlc3bnNzYW55WGZENWMxUmMKLS0tIFdTL2E0cUlQdmtCNm10eStDVUxX
            SzlpTnRhdy8xNVJQVDVmUWtJVGtRajQKQOa5pNve1/r/O4VKvz4r36EQUSKJTggR
            SQMgDxh8Ty4lN78hfW+FQizg2eJhURpcVnt7cPPvjQlpqtyFJXvsDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T23:49:30Z"
    mac: ENC[AES256_GCM,data:OvaFmJ/vwHUA0JP+YYbGk6ppD9VtGMYWr3xc9iYSAjb4tQxF4TfpCQM0mnegNmSMujB/AmiWZypgAPAEAJVvUX2suPO2+GL2AkpT7VpOBr1HeFWPx4XFhWzmBEX3R+fm1vhdNPp+/jc9iJoSwZKInZYUiItEGoz2VSKZ/W7hDX0=,iv:gCRfIhnHhaYaXdDbFwsY+umsh6WOjvuBh+m3M8SSCwk=,tag:fewEnkFQP0aRK3c3eLpu4Q==,type:str]
    version: 3.13.3
