apiVersion: v1
kind: Secret
metadata:
    name: pg-backup-s3
    namespace: database
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:jJWuFh+zlNGMkold+WlfFww6+eQ=,iv:DZTYTsZ6474rXnXA9iiv+YEmO3Pyx/lwaL0Gtj+fTcM=,tag:27i8/s9A9j9qpI2dzrPpww==,type:str]
    SECRET_ACCESS_KEY: ENC[AES256_GCM,data:9Z6R0Ywa/HsWU1shRw7l3ezWSegEOcJ0RlIYegVtu5eKv0q9zuoS2g==,iv:Av+PSNTIuHTDpo3Sy9ZkM5eoT5VLzGC2OeTJJNAyPgM=,tag:aQ5bZ5sWON7GjOVxubf+Lw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzZ1NqaWpVaHgzNVhzM0E5
            eS9SbjZEbG5ud1RGSUVXSThqYlh6bXpjNFJrClcvTzhJVEQ5Q3plS2xDdkJ1bGhR
            KzU5WUgwNmtpYk9WY0JZM1BWOGx0R28KLS0tIHZTUitiano0akVRanJYTXpnZTE0
            c2NYN1p0NER5U082SlJKY3BxbmZ4b00KM93YUxC5038gEuawy5pZ3KKuot0ONPV2
            opv3J78Pdc74EvYvgeXI6459Dw0PJvZwbvKg591dobeG54LXGBqw9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1sgwm6ckyjns0grwu6hsc6zhh2esh3ja7xmwynkw9ukc3ygq8tf8qsgusx5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLTmlHY0xITGlmZWUxSkVi
            WmVlOEFzQ0RnL2hwYlhnNWJXdUVpTVV1eWxVCkdWYURRcnNWdnlCNURpdXNkb2dZ
            dGpNQXRGb1dJUGRYVEw1WENzS1VEaHMKLS0tIGdxM3JEOUhYckl0bEIydktlZGtz
            L0Y2RU9CMHlxZTE5RllVVDZPS094Q1EKIpBCh2us+t6AH8Czd5eSdj+zi1b9wV6J
            AyZSZqNS9QP/Ph3wht5tKXk7C47dQ7V1NaOMue6FPFHNnacyv1N/jg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16y5yn6mddywkr8vwf5xjuukw6c33vy3yp2gtpmafr09fltlw3qfq7repy8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T18:34:53Z"
    mac: ENC[AES256_GCM,data:LaaQZQa4AAmqb/lMFHv/bLaIdhr9alF+dPTXtaMYQ1+/LT+EWwMdxuUwzRm0/3Fj59L9YmJqd7Matct9hAWuB/zckDmfSxLs+xHVGMWABkmu2CqtphLDJnQO82xgGqNBhh2RqarMMlHT5xXoKlk8YNF3aPyirRw2xalQvjuGez0=,iv:qeWzgEjPL6hT49EPK/h1NNfEeQJRPxM3pcEtCAS2ngY=,tag:iOie4ofCRkck2patcVBYjQ==,type:str]
    version: 3.13.3
