locals {
  # Every hostname this module publishes, as a WAF host match. Built from the
  # same variables the DNS records are, so a hostname added there cannot be
  # forgotten here.
  waf_all_hosts = format(
    "http.host in {%s}",
    join(" ", [for h in concat([var.hostname], [for e in var.extra_hostnames : e.hostname]) : "\"${h}\""])
  )

  tunnel_name = "xenopsbase-${var.environment}"

  # Extra hostnames that opted into Access. Kept as a local so the opt-in is
  # read once and every consumer below agrees about what is protected.
  access_dashboard_hostnames = var.manage_access ? toset([
    for h in var.extra_hostnames : h.hostname if h.access
  ]) : toset([])

  # A tunnel is reached by CNAME to this synthetic hostname. It is derived from
  # the tunnel's UUID, which does not change when the cluster is rebuilt --
  # which is the whole reason DNS is stable here.
  tunnel_target = "${cloudflare_zero_trust_tunnel_cloudflared.this.id}.cfargotunnel.com"
}

# ------------------------------------------------------------------------------
# The tunnel
#
# cloudflared runs INSIDE the cluster and dials OUT to Cloudflare. Nothing
# listens publicly, so there is no load balancer to pay for and no public
# listener to defend. That is the same instinct as ADR-0006 applied to
# application traffic rather than to the control plane.
# ------------------------------------------------------------------------------

resource "cloudflare_zero_trust_tunnel_cloudflared" "this" {
  account_id = var.account_id
  name       = local.tunnel_name

  # Ingress rules live in Cloudflare rather than in a local config file, so they
  # are managed here rather than by whatever happens to be on the node.
  config_src = "cloudflare"

  lifecycle {
    # The secret is generated by Cloudflare on creation. Terraform cannot read
    # it back, so without this every plan shows a spurious change and every
    # apply would recreate the tunnel -- which would change the tunnel ID, and
    # with it the DNS target.
    ignore_changes = [tunnel_secret]
  }
}

# The connector credential is not an attribute of the tunnel resource in
# provider v5 -- it is fetched separately. cloudflared in-cluster (T-2.2)
# authenticates with this.
data "cloudflare_zero_trust_tunnel_cloudflared_token" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
}

resource "cloudflare_dns_record" "extra" {
  for_each = { for h in var.extra_hostnames : h.hostname => h }

  zone_id = var.zone_id
  name    = each.value.hostname
  type    = "CNAME"
  content = local.tunnel_target
  proxied = true
  ttl     = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
  source     = "cloudflare"

  config = {
    ingress = concat(
      [
        {
          hostname = var.hostname
          service  = var.tunnel_service
        },
      ],
      # Additional hostnames, each to its own in-cluster service. Placed BEFORE
      # the catch-all: Cloudflare evaluates these top to bottom and the
      # catch-all matches everything, so a rule after it is unreachable.
      [
        for h in var.extra_hostnames : {
          hostname = h.hostname
          service  = h.service
        }
      ],
      # Cloudflare requires a final catch-all with no hostname. Anything that
      # reaches the tunnel without matching a rule above gets a 404 rather than
      # being forwarded somewhere unintended.
      [
        {
          service = "http_status:404"
        },
      ],
    )
  }
}

# ------------------------------------------------------------------------------
# DNS
# ------------------------------------------------------------------------------

resource "cloudflare_dns_record" "app" {
  zone_id = var.zone_id
  name    = var.hostname
  type    = "CNAME"
  content = local.tunnel_target

  # proxied is not optional here: a cfargotunnel.com target is only reachable
  # through Cloudflare's edge. It is also what terminates TLS for the client.
  proxied = true

  # ttl must be 1 (automatic) whenever proxied is true; Cloudflare rejects
  # anything else.
  ttl = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

# ------------------------------------------------------------------------------
# Zone-wide settings — OFF by default
#
# This zone hosts a live company site. See variables.tf for why these are opt-in
# rather than applied as a matter of course.
# ------------------------------------------------------------------------------

resource "cloudflare_zone_setting" "tls_mode" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "ssl"
  value      = var.zone_tls_mode
}

resource "cloudflare_zone_setting" "always_use_https" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "always_use_https"
  value      = "on"
}

resource "cloudflare_zone_setting" "min_tls_version" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "min_tls_version"
  value      = "1.2"
}

# ------------------------------------------------------------------------------
# WAF — OFF by default
#
# Every expression below is anchored to hostnames this module owns. A zone-scoped
# rule that forgets that anchor evaluates against everything else in the zone,
# and a wrong rule there blocks real traffic rather than merely failing a test.
# ------------------------------------------------------------------------------

// ------------------------------------------------------------------------------
// RATE LIMITING AT THE EDGE (T-8.3, #61).
//
// The gateway limits per client too (RateLimiterConfiguration), and the two are
// not redundant. They cover different surfaces, and neither covers the other's:
//
//   - Spring Cloud Gateway's RequestRateLimiter is a route filter, so it applies
//     to what the gateway PROXIES. Identity is not proxied: Keycloak is its own
//     hostname, delivered by the tunnel straight to ingress-nginx, and never
//     passes through the gateway at all. The login surface -- the one worth
//     protecting from credential stuffing -- is unreachable from there.
//   - The gateway's per-IP key is only meaningful because Cloudflare writes the
//     forwarded header. `trusted-proxies` is '.*' for reasons measured on the
//     live cluster; the edge is what makes that safe.
//
// WHY EXACTLY ONE RULE
//
// Cloudflare's free plan allows one rate limiting rule per zone, requires
// `cf.colo.id` among the characteristics -- so the count is per data centre
// rather than global, and the effective ceiling is higher than the number
// written here -- and permits exactly one window:
//
//   400 Bad Request
//   "not entitled to use the period 60, can only use a period among [10]"
//     pointer: /rules/0/ratelimit/period
//
// That is the API refusing the first version of this resource, which asked for
// 60. Worth reading twice: `terraform validate` accepted it, `terraform plan`
// accepted it, and CI's plan job accepted it. Plan-tier entitlements are
// enforced at the API and nowhere earlier, so the only thing that could have
// found this was an apply.
//
// All three are constraints of the plan rather than choices, and all three are
// easier to read here than to rediscover.
//
// So the one rule goes where it buys the most: the hostnames NOT behind
// Cloudflare Access. Everything behind Access already requires an identity
// before a request reaches the origin at all (T-8.6, #149); the hostnames
// without it are the entire unauthenticated public surface, which today means
// identity.
//
// Derived rather than named. A hostname added with `access = false` is added to
// this rule by the same edit, instead of by somebody remembering.
locals {
  rate_limited_hosts = [for e in var.extra_hostnames : e.hostname if !e.access]

  rate_limit_expression = length(local.rate_limited_hosts) == 0 ? null : format(
    "http.host in {%s}",
    join(" ", [for h in local.rate_limited_hosts : "\"${h}\""])
  )
}

resource "cloudflare_ruleset" "rate_limit" {
  count = var.manage_waf && local.rate_limit_expression != null ? 1 : 0

  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} rate limiting"
  kind    = "zone"
  phase   = "http_ratelimit"

  rules = [
    {
      action      = "block"
      description = "rate limit unauthenticated xenopsbase ${var.environment} hostnames per client"
      expression  = local.rate_limit_expression
      enabled     = true

      ratelimit = {
        // ip.src is the client; cf.colo.id is required by the free plan and
        // makes the count per data centre. Together they mean "one client, one
        // colo", which is the closest this plan gets to per-client.
        characteristics = ["ip.src", "cf.colo.id"]

        // 50 requests per 10 seconds -- the same rate as the 300/minute this
        // asked for before the API refused the window, expressed in the only
        // window the plan allows. Far above a person logging in and far below a
        // credential-stuffing loop; like the gateway's numbers this is a ceiling
        // rather than a tuning.
        //
        // The shorter window is not purely a downgrade. It reacts faster, and it
        // is burstier: a client may spend the whole allowance in one second and
        // wait, where a 60s window would have averaged it out. For a login
        // surface that trade is the right way round.
        period              = 10
        requests_per_period = 50

        // Equal to the window, which is the conservative reading of a plan that
        // permits one period: block for as long as the thing being counted.
        // Long enough to be a real cost to a script, short enough that a false
        // positive is an annoyance rather than a support ticket -- the same
        // trade the WAF rule below makes by choosing a challenge over a block.
        mitigation_timeout = 10
      }
    },
  ]
}

resource "cloudflare_ruleset" "waf" {
  count = var.manage_waf ? 1 : 0

  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} baseline"
  kind    = "zone"
  phase   = "http_request_firewall_custom"

  rules = [
    {
      # Administrative and metadata paths are never legitimate from the public
      # internet. Covers every hostname this module owns -- identity included,
      # since auth-*.  is the one most worth probing -- and nothing else in the
      # zone.
      action      = "block"
      description = "block admin and metadata paths on xenopsbase ${var.environment} hostnames"
      expression  = "(${local.waf_all_hosts} and (starts_with(http.request.uri.path, \"/actuator\") or starts_with(http.request.uri.path, \"/.git\") or starts_with(http.request.uri.path, \"/.env\")))"
      enabled     = true
    },
    {
      # Managed challenge rather than block: bot scoring is probabilistic, and
      # blocking outright turns a false positive into a support ticket.
      #
      # Deliberately NOT applied to the identity hostnames. A challenge is a
      # browser interstitial, and the OIDC endpoints are called by things that
      # cannot solve one: the PKCE code exchange is a back-channel POST, and
      # service-account token requests have no browser at all. Challenging them
      # returns HTML to a client expecting JSON, which surfaces as an
      # unintelligible login failure rather than as a WAF event.
      action      = "managed_challenge"
      description = "challenge likely automated traffic on ${var.hostname}"
      expression  = "(http.host eq \"${var.hostname}\" and cf.client.bot and not cf.verified_bot_category in {\"Search Engine Crawler\" \"Monitoring & Analytics\"})"
      enabled     = true
    },
  ]
}

# ------------------------------------------------------------------------------
# Request header transform: tell the origin what port the public endpoint is on.
#
# TLS terminates here, and the tunnel delivers plain HTTP to ingress-nginx, which
# therefore listens on 80 and reports X-Forwarded-Port from its own $server_port.
# The origin was being told:
#
#     X-Forwarded-Proto: https
#     X-Forwarded-Port:  80
#
# which describes no endpoint that exists. Spring believes both and builds
# absolute URLs as https://host:80/..., because 80 is not the default port for
# https and so gets rendered. Keycloak matches redirect_uri by exact string, so
# every OIDC login was rejected with "Invalid parameter: redirect_uri" while the
# gateway, the realm, the ingress and the tunnel all reported healthy.
#
# WHY HERE AND NOT AT THE INGRESS
#
# Cloudflare is the only component that knows the public port, so this is the
# only layer that can state it truthfully rather than infer it.
#
# The obvious in-cluster fixes were tried and measured against a header echo
# behind the same ingress:
#
#   - ingress-nginx proxy-set-headers APPENDS rather than replaces. Setting
#     X-Forwarded-Port there produced "80, 443", and every consumer takes the
#     first value, so it changed nothing.
#   - a configuration-snippet annotation could replace it, but snippets are
#     disabled by default in current ingress-nginx precisely because they let
#     any namespace holding Ingress permission inject arbitrary nginx config.
#
# The same echo proved the remaining half: with use-forwarded-headers, nginx
# DOES adopt an incoming X-Forwarded-Port. Sending 443 from here yields 443 at
# the origin. That is what this rule does.
#
# It also fixes every other absolute URL the origin builds -- logout redirects,
# links in mail -- not only the OIDC one, which a per-application override would
# have left broken.
# ------------------------------------------------------------------------------

resource "cloudflare_ruleset" "request_headers" {
  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} forwarded headers"
  kind    = "zone"
  phase   = "http_request_late_transform"

  rules = [
    {
      action = "rewrite"
      action_parameters = {
        headers = {
          "X-Forwarded-Port" = {
            operation = "set"
            value     = "443"
          }

          # Overwritten from the real Host, never taken from the caller.
          #
          # Nothing in the chain was replacing this, so a client could send
          # X-Forwarded-Host and choose the origin the application put in the
          # absolute URLs it hands out. Verified: a request carrying
          # `X-Forwarded-Host: evil.example.com` came back with pagination Link
          # headers pointing at https://evil.example.com/... . Whoever follows
          # those links has been redirected by the caller, using the server's own
          # response as the vehicle.
          #
          # ingress-nginx does not help here. use-forwarded-headers is on, which
          # is what makes it adopt the X-Forwarded-Port above, and adopting means
          # trusting the incoming value for this header too.
          "X-Forwarded-Host" = {
            operation  = "set"
            expression = "http.host"
          }

          # Stripped, not set. Only Spring Cloud Gateway knows what prefix it
          # removed, and it states it on the internal hop; there is no correct
          # value to put here, and any value from the caller is wrong.
          #
          # Left alone, this reaches the gateway, whose own forwarded-header
          # handling applies it BEFORE route predicates run -- so
          # `X-Forwarded-Prefix: /injected` moved every path out from under
          # `Path=/services/core/**` and the gateway stopped routing to core at
          # all. A caller could turn routing off from outside.
          "X-Forwarded-Prefix" = {
            operation = "remove"
          }
        }
      }
      # Scoped to this module's hostnames, like the WAF rules above. A zone-wide
      # header rewrite would apply to anything else living in the zone.
      expression  = "(${local.waf_all_hosts})"
      description = "state the real public port for xenopsbase ${var.environment} origins"
      enabled     = true
    },
  ]
}

# ------------------------------------------------------------------------------
# Cloudflare Access in front of the application (T-8.6, #149).
#
# dev is reachable from the internet, and the credentials that get past its
# login are in this repository, which is public. That was acceptable while the
# realm was empty and login did not work; T-3.13 made login work and put a
# document upload behind it, and nothing announced that the premise had changed.
#
# Access is chosen over moving the passwords into SOPS because it touches the
# realm not at all. Editing the realm means a KeycloakRealmImport delete and
# re-import, which issues every user a new `sub` and orphans every document
# owned under the old one (#147). Hiding the key would have cost the data.
#
# The application login page is what becomes unreachable, not Keycloak. Identity
# stays public on its own hostname, because the OIDC flow redirects the user's
# browser there and a challenge in that path breaks the back-channel code
# exchange (the same reasoning as the WAF rules above).
# ------------------------------------------------------------------------------

resource "cloudflare_zero_trust_access_service_token" "automation" {
  count = var.manage_access ? 1 : 0

  account_id = var.account_id
  name       = var.access_service_token_name
}

resource "cloudflare_zero_trust_access_application" "app" {
  # access_protect_app is the T-3.18 experiment switch and is true everywhere
  # except while that investigation is running. It gates THIS resource only --
  # the dashboards, policies and service token below are deliberately outside
  # it, because Prometheus and Alertmanager have no login of their own and
  # Access is their only control.
  count = var.manage_access && var.access_protect_app ? 1 : 0

  account_id = var.account_id
  name       = "xenopsbase-${var.environment}"
  domain     = var.hostname
  type       = "self_hosted"

  # A day, so the team is not re-authenticating through the working session
  # that a dev environment exists to support.
  session_duration = "24h"

  policies = [
    {
      id         = cloudflare_zero_trust_access_policy.team[0].id
      precedence = 1
    },
    {
      id         = cloudflare_zero_trust_access_policy.automation[0].id
      precedence = 2
    },
  ]
}

# The operator dashboards -- Grafana, Prometheus, Alertmanager, Argo CD.
#
# A separate resource from the application above rather than one for_each over
# both, because the two are protected for different reasons and by different
# policies. Merging them would also rekey the existing application in state,
# and a destroy-and-recreate of an Access application means app-dev is public
# for the width of the apply.
#
# WHY THIS MATTERS MORE HERE THAN FOR THE APPLICATION. Prometheus and
# Alertmanager have no authentication of their own at all -- there is no login
# to fail. Access is not defence in depth for those two, it is the only control,
# and Alertmanager's API can silence alerts. Grafana and Argo CD do have their
# own logins, so for them Access is the outer layer.
#
# TEAM ONLY, DELIBERATELY. The service token is absent from this list. It exists
# so CI can drive the application through smoke and promotion (see
# .github/workflows/smoke.yml); nothing automated reads a dashboard. Including
# it anyway would hand every CI run the ability to silence alerting, which is a
# wider grant than anything asked for it.
resource "cloudflare_zero_trust_access_application" "dashboard" {
  for_each = local.access_dashboard_hostnames

  account_id = var.account_id

  # The leftmost label, so the Zero Trust dashboard lists these as
  # "xenopsbase-dev grafana-dev" rather than four near-identical names.
  name   = "xenopsbase-${var.environment} ${split(".", each.value)[0]}"
  domain = each.value
  type   = "self_hosted"

  # Matches the application. Re-authenticating mid-session while chasing a
  # graph is the fastest way to make people stop opening the graph.
  session_duration = "24h"

  policies = [
    {
      id         = cloudflare_zero_trust_access_policy.team[0].id
      precedence = 1
    },
  ]
}

resource "cloudflare_zero_trust_access_policy" "team" {
  count = var.manage_access ? 1 : 0

  account_id = var.account_id
  name       = "xenopsbase-${var.environment} team"
  decision   = "allow"

  # A group reference, not a list of addresses (T-6.11, #335). The membership
  # lives in Cloudflare, so this include is identical in every environment and
  # in CI -- which is the point: there is no longer a value that a runner can
  # fail to reconstruct.
  include = [
    {
      group = {
        id = var.access_group_id
      }
    }
  ]
}

resource "cloudflare_zero_trust_access_policy" "automation" {
  count = var.manage_access ? 1 : 0

  account_id = var.account_id
  name       = "xenopsbase-${var.environment} automation"
  decision   = "non_identity"

  # Service token rather than an IP allowlist or a bypass. A bypass policy
  # would make the endpoint public again for anyone who found the path, and CI
  # egress addresses are far too broad to allowlist -- which is one of the
  # reasons this project moved off an IP allowlist in ADR-0006.
  include = [
    {
      service_token = {
        token_id = cloudflare_zero_trust_access_service_token.automation[0].id
      }
    }
  ]
}

# The two assertions that used to be `check` blocks here are now validation
# blocks on the variables they are about, in variables.tf.
#
# They did not move for tidiness. Neither of them REFUSED anything: a check
# block's failed assertion is a warning and `terraform plan` still exits 0, so
# "Refuses the combination that ... locks everyone out" was a claim the
# mechanism could not keep. The empty allow list reached Cloudflare and was
# rejected mid-apply, after the run had already destroyed the Access
# application (T-6.11, #335).
