locals {
  # Every hostname this module publishes, as a WAF host match. Built from the
  # same variables the DNS records are, so a hostname added there cannot be
  # forgotten here.
  waf_all_hosts = format(
    "http.host in {%s}",
    join(" ", [for h in concat([var.hostname], [for e in var.extra_hostnames : e.hostname]) : "\"${h}\""])
  )

  tunnel_name = "xenopsbase-${var.environment}"

  # A tunnel is reached by CNAME to this synthetic hostname. It is derived from
  # the tunnel's UUID, which does not change when the cluster is rebuilt --
  # which is the whole reason DNS is stable here.
  tunnel_target = "${cloudflare_zero_trust_tunnel_cloudflared.this.id}.cfargotunnel.com"
}

# ------------------------------------------------------------------------------
# The tunnel
#
# cloudflared runs INSIDE the cluster and dials OUT to Cloudflare. Nothing
# listens publicly, so there is no load balancer to pay for and no public
# listener to defend. That is the same instinct as ADR-0006 applied to
# application traffic rather than to the control plane.
# ------------------------------------------------------------------------------

resource "cloudflare_zero_trust_tunnel_cloudflared" "this" {
  account_id = var.account_id
  name       = local.tunnel_name

  # Ingress rules live in Cloudflare rather than in a local config file, so they
  # are managed here rather than by whatever happens to be on the node.
  config_src = "cloudflare"

  lifecycle {
    # The secret is generated by Cloudflare on creation. Terraform cannot read
    # it back, so without this every plan shows a spurious change and every
    # apply would recreate the tunnel -- which would change the tunnel ID, and
    # with it the DNS target.
    ignore_changes = [tunnel_secret]
  }
}

# The connector credential is not an attribute of the tunnel resource in
# provider v5 -- it is fetched separately. cloudflared in-cluster (T-2.2)
# authenticates with this.
data "cloudflare_zero_trust_tunnel_cloudflared_token" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
}

resource "cloudflare_dns_record" "extra" {
  for_each = { for h in var.extra_hostnames : h.hostname => h }

  zone_id = var.zone_id
  name    = each.value.hostname
  type    = "CNAME"
  content = local.tunnel_target
  proxied = true
  ttl     = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
  source     = "cloudflare"

  config = {
    ingress = concat(
      [
        {
          hostname = var.hostname
          service  = var.tunnel_service
        },
      ],
      # Additional hostnames, each to its own in-cluster service. Placed BEFORE
      # the catch-all: Cloudflare evaluates these top to bottom and the
      # catch-all matches everything, so a rule after it is unreachable.
      [
        for h in var.extra_hostnames : {
          hostname = h.hostname
          service  = h.service
        }
      ],
      # Cloudflare requires a final catch-all with no hostname. Anything that
      # reaches the tunnel without matching a rule above gets a 404 rather than
      # being forwarded somewhere unintended.
      [
        {
          service = "http_status:404"
        },
      ],
    )
  }
}

# ------------------------------------------------------------------------------
# DNS
# ------------------------------------------------------------------------------

resource "cloudflare_dns_record" "app" {
  zone_id = var.zone_id
  name    = var.hostname
  type    = "CNAME"
  content = local.tunnel_target

  # proxied is not optional here: a cfargotunnel.com target is only reachable
  # through Cloudflare's edge. It is also what terminates TLS for the client.
  proxied = true

  # ttl must be 1 (automatic) whenever proxied is true; Cloudflare rejects
  # anything else.
  ttl = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

# ------------------------------------------------------------------------------
# Zone-wide settings — OFF by default
#
# This zone hosts a live company site. See variables.tf for why these are opt-in
# rather than applied as a matter of course.
# ------------------------------------------------------------------------------

resource "cloudflare_zone_setting" "tls_mode" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "ssl"
  value      = var.zone_tls_mode
}

resource "cloudflare_zone_setting" "always_use_https" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "always_use_https"
  value      = "on"
}

resource "cloudflare_zone_setting" "min_tls_version" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "min_tls_version"
  value      = "1.2"
}

# ------------------------------------------------------------------------------
# WAF — OFF by default
#
# Every expression below is anchored to hostnames this module owns. A zone-scoped
# rule that forgets that anchor evaluates against everything else in the zone,
# and a wrong rule there blocks real traffic rather than merely failing a test.
# ------------------------------------------------------------------------------

resource "cloudflare_ruleset" "waf" {
  count = var.manage_waf ? 1 : 0

  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} baseline"
  kind    = "zone"
  phase   = "http_request_firewall_custom"

  rules = [
    {
      # Administrative and metadata paths are never legitimate from the public
      # internet. Covers every hostname this module owns -- identity included,
      # since auth-*.  is the one most worth probing -- and nothing else in the
      # zone.
      action      = "block"
      description = "block admin and metadata paths on xenopsbase ${var.environment} hostnames"
      expression  = "(${local.waf_all_hosts} and (starts_with(http.request.uri.path, \"/actuator\") or starts_with(http.request.uri.path, \"/.git\") or starts_with(http.request.uri.path, \"/.env\")))"
      enabled     = true
    },
    {
      # Managed challenge rather than block: bot scoring is probabilistic, and
      # blocking outright turns a false positive into a support ticket.
      #
      # Deliberately NOT applied to the identity hostnames. A challenge is a
      # browser interstitial, and the OIDC endpoints are called by things that
      # cannot solve one: the PKCE code exchange is a back-channel POST, and
      # service-account token requests have no browser at all. Challenging them
      # returns HTML to a client expecting JSON, which surfaces as an
      # unintelligible login failure rather than as a WAF event.
      action      = "managed_challenge"
      description = "challenge likely automated traffic on ${var.hostname}"
      expression  = "(http.host eq \"${var.hostname}\" and cf.client.bot and not cf.verified_bot_category in {\"Search Engine Crawler\" \"Monitoring & Analytics\"})"
      enabled     = true
    },
  ]
}

# ------------------------------------------------------------------------------
# Request header transform: tell the origin what port the public endpoint is on.
#
# TLS terminates here, and the tunnel delivers plain HTTP to ingress-nginx, which
# therefore listens on 80 and reports X-Forwarded-Port from its own $server_port.
# The origin was being told:
#
#     X-Forwarded-Proto: https
#     X-Forwarded-Port:  80
#
# which describes no endpoint that exists. Spring believes both and builds
# absolute URLs as https://host:80/..., because 80 is not the default port for
# https and so gets rendered. Keycloak matches redirect_uri by exact string, so
# every OIDC login was rejected with "Invalid parameter: redirect_uri" while the
# gateway, the realm, the ingress and the tunnel all reported healthy.
#
# WHY HERE AND NOT AT THE INGRESS
#
# Cloudflare is the only component that knows the public port, so this is the
# only layer that can state it truthfully rather than infer it.
#
# The obvious in-cluster fixes were tried and measured against a header echo
# behind the same ingress:
#
#   - ingress-nginx proxy-set-headers APPENDS rather than replaces. Setting
#     X-Forwarded-Port there produced "80, 443", and every consumer takes the
#     first value, so it changed nothing.
#   - a configuration-snippet annotation could replace it, but snippets are
#     disabled by default in current ingress-nginx precisely because they let
#     any namespace holding Ingress permission inject arbitrary nginx config.
#
# The same echo proved the remaining half: with use-forwarded-headers, nginx
# DOES adopt an incoming X-Forwarded-Port. Sending 443 from here yields 443 at
# the origin. That is what this rule does.
#
# It also fixes every other absolute URL the origin builds -- logout redirects,
# links in mail -- not only the OIDC one, which a per-application override would
# have left broken.
# ------------------------------------------------------------------------------

resource "cloudflare_ruleset" "request_headers" {
  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} forwarded headers"
  kind    = "zone"
  phase   = "http_request_late_transform"

  rules = [
    {
      action = "rewrite"
      action_parameters = {
        headers = {
          "X-Forwarded-Port" = {
            operation = "set"
            value     = "443"
          }

          # Overwritten from the real Host, never taken from the caller.
          #
          # Nothing in the chain was replacing this, so a client could send
          # X-Forwarded-Host and choose the origin the application put in the
          # absolute URLs it hands out. Verified: a request carrying
          # `X-Forwarded-Host: evil.example.com` came back with pagination Link
          # headers pointing at https://evil.example.com/... . Whoever follows
          # those links has been redirected by the caller, using the server's own
          # response as the vehicle.
          #
          # ingress-nginx does not help here. use-forwarded-headers is on, which
          # is what makes it adopt the X-Forwarded-Port above, and adopting means
          # trusting the incoming value for this header too.
          "X-Forwarded-Host" = {
            operation  = "set"
            expression = "http.host"
          }

          # Stripped, not set. Only Spring Cloud Gateway knows what prefix it
          # removed, and it states it on the internal hop; there is no correct
          # value to put here, and any value from the caller is wrong.
          #
          # Left alone, this reaches the gateway, whose own forwarded-header
          # handling applies it BEFORE route predicates run -- so
          # `X-Forwarded-Prefix: /injected` moved every path out from under
          # `Path=/services/core/**` and the gateway stopped routing to core at
          # all. A caller could turn routing off from outside.
          "X-Forwarded-Prefix" = {
            operation = "remove"
          }
        }
      }
      # Scoped to this module's hostnames, like the WAF rules above. A zone-wide
      # header rewrite would apply to anything else living in the zone.
      expression  = "(${local.waf_all_hosts})"
      description = "state the real public port for xenopsbase ${var.environment} origins"
      enabled     = true
    },
  ]
}
