locals {
  tunnel_name = "xenopsbase-${var.environment}"

  # A tunnel is reached by CNAME to this synthetic hostname. It is derived from
  # the tunnel's UUID, which does not change when the cluster is rebuilt --
  # which is the whole reason DNS is stable here.
  tunnel_target = "${cloudflare_zero_trust_tunnel_cloudflared.this.id}.cfargotunnel.com"
}

# ------------------------------------------------------------------------------
# The tunnel
#
# cloudflared runs INSIDE the cluster and dials OUT to Cloudflare. Nothing
# listens publicly, so there is no load balancer to pay for and no public
# listener to defend. That is the same instinct as ADR-0006 applied to
# application traffic rather than to the control plane.
# ------------------------------------------------------------------------------

resource "cloudflare_zero_trust_tunnel_cloudflared" "this" {
  account_id = var.account_id
  name       = local.tunnel_name

  # Ingress rules live in Cloudflare rather than in a local config file, so they
  # are managed here rather than by whatever happens to be on the node.
  config_src = "cloudflare"

  lifecycle {
    # The secret is generated by Cloudflare on creation. Terraform cannot read
    # it back, so without this every plan shows a spurious change and every
    # apply would recreate the tunnel -- which would change the tunnel ID, and
    # with it the DNS target.
    ignore_changes = [tunnel_secret]
  }
}

# The connector credential is not an attribute of the tunnel resource in
# provider v5 -- it is fetched separately. cloudflared in-cluster (T-2.2)
# authenticates with this.
data "cloudflare_zero_trust_tunnel_cloudflared_token" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
}

resource "cloudflare_dns_record" "extra" {
  for_each = { for h in var.extra_hostnames : h.hostname => h }

  zone_id = var.zone_id
  name    = each.value.hostname
  type    = "CNAME"
  content = local.tunnel_target
  proxied = true
  ttl     = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

resource "cloudflare_zero_trust_tunnel_cloudflared_config" "this" {
  account_id = var.account_id
  tunnel_id  = cloudflare_zero_trust_tunnel_cloudflared.this.id
  source     = "cloudflare"

  config = {
    ingress = concat(
      [
        {
          hostname = var.hostname
          service  = var.tunnel_service
        },
      ],
      # Additional hostnames, each to its own in-cluster service. Placed BEFORE
      # the catch-all: Cloudflare evaluates these top to bottom and the
      # catch-all matches everything, so a rule after it is unreachable.
      [
        for h in var.extra_hostnames : {
          hostname = h.hostname
          service  = h.service
        }
      ],
      # Cloudflare requires a final catch-all with no hostname. Anything that
      # reaches the tunnel without matching a rule above gets a 404 rather than
      # being forwarded somewhere unintended.
      [
        {
          service = "http_status:404"
        },
      ],
    )
  }
}

# ------------------------------------------------------------------------------
# DNS
# ------------------------------------------------------------------------------

resource "cloudflare_dns_record" "app" {
  zone_id = var.zone_id
  name    = var.hostname
  type    = "CNAME"
  content = local.tunnel_target

  # proxied is not optional here: a cfargotunnel.com target is only reachable
  # through Cloudflare's edge. It is also what terminates TLS for the client.
  proxied = true

  # ttl must be 1 (automatic) whenever proxied is true; Cloudflare rejects
  # anything else.
  ttl = 1

  comment = "Managed by xenopsbase-stemcell (${var.environment}). Do not edit in the console."
}

# ------------------------------------------------------------------------------
# Zone-wide settings — OFF by default
#
# This zone hosts a live company site. See variables.tf for why these are opt-in
# rather than applied as a matter of course.
# ------------------------------------------------------------------------------

resource "cloudflare_zone_setting" "tls_mode" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "ssl"
  value      = var.zone_tls_mode
}

resource "cloudflare_zone_setting" "always_use_https" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "always_use_https"
  value      = "on"
}

resource "cloudflare_zone_setting" "min_tls_version" {
  count = var.manage_zone_settings ? 1 : 0

  zone_id    = var.zone_id
  setting_id = "min_tls_version"
  value      = "1.2"
}

# ------------------------------------------------------------------------------
# WAF — OFF by default
#
# Every expression below is anchored to var.hostname. A zone-scoped rule that
# forgets that anchor evaluates against the company site too, and a wrong rule
# there blocks real customers rather than merely failing a test.
# ------------------------------------------------------------------------------

resource "cloudflare_ruleset" "waf" {
  count = var.manage_waf ? 1 : 0

  zone_id = var.zone_id
  name    = "xenopsbase-${var.environment} baseline"
  kind    = "zone"
  phase   = "http_request_firewall_custom"

  rules = [
    {
      # Administrative and metadata paths are never legitimate from the public
      # internet. Scoped to this hostname so the rest of the zone is untouched.
      action      = "block"
      description = "block admin and metadata paths on ${var.hostname}"
      expression  = "(http.host eq \"${var.hostname}\" and (starts_with(http.request.uri.path, \"/actuator\") or starts_with(http.request.uri.path, \"/.git\") or starts_with(http.request.uri.path, \"/.env\")))"
      enabled     = true
    },
    {
      # Managed challenge rather than block: bot scoring is probabilistic, and
      # blocking outright turns a false positive into a support ticket.
      action      = "managed_challenge"
      description = "challenge likely automated traffic on ${var.hostname}"
      expression  = "(http.host eq \"${var.hostname}\" and cf.client.bot and not cf.verified_bot_category in {\"Search Engine Crawler\" \"Monitoring & Analytics\"})"
      enabled     = true
    },
  ]
}
