#!/usr/bin/env bash
#
# Checks that the credentials in the environment can actually reach every API a
# module is about to use — before Terraform starts changing anything.
#
# WHY THIS EXISTS
#
# Four applies in this project have been stopped by a credential's SCOPE rather
# than by the credential being wrong or absent:
#
#   the R2 token, which is object-storage scoped and cannot touch DNS
#   the edge token, which could not read Zone Settings
#   the Brevo SMTP key, which had IP authorisation enabled
#   the edge token again, which could not write WAF rulesets
#
# Every one surfaced the same way: a generic "Authentication error" from deep
# inside an apply, with no indication of which permission was missing. The WAF
# one is the instructive case — it failed AFTER three resources had already been
# created, leaving the zone half-configured, exiting non-zero, and saying
# nothing about which half. A human reading the output can work it out. T-6.3
# applies these modules with nobody reading the output.
#
# So this asks each API whether the token can reach it, and names the exact
# permission when it cannot.
#
# WHAT THIS CANNOT TELL YOU
#
# Cloudflare's /user/tokens/verify reports that a token is active, not what it
# may do, and reading a token's own policies needs a permission the token will
# not have. So these are READ probes, and Cloudflare's Edit implies Read: a
# token with "Zone WAF Read" passes the WAF probe here and still fails to write
# a ruleset.
#
# That is a real gap, and it is worth being clear that it is a gap. It would not
# have missed any of the four failures above, because in each the permission was
# absent altogether rather than read-only. Treat a pass as "the token can see
# this API", not as "the apply will succeed".
#
# Read-only. Every request below is a GET.

set -euo pipefail

MODULE="${1:?usage: preflight.sh <edge|mail-dns|cluster|storage> [env]}"
ENVIRONMENT="${2:-dev}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

fail=0
pass() { printf '  \033[32m✓\033[0m %s\n' "$1"; }
bad() {
  printf '  \033[31m✗\033[0m %s\n' "$1"
  [ -n "${2:-}" ] && printf '      %s\n' "$2"
  fail=1
}

# Reads a bare `key = "value"` out of a tfvars file. Deliberately not a parser:
# these files are generated by hand from an example and stay flat.
tfvar() {
  local file="$1" key="$2"
  [ -f "$file" ] || return 0
  sed -n "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*\"\(.*\)\"[[:space:]]*$/\1/p" "$file" | head -1
}

tfbool() {
  local file="$1" key="$2"
  [ -f "$file" ] || return 0
  sed -n "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*\([a-z]*\)[[:space:]]*$/\1/p" "$file" | head -1
}

# $1 url, $2 description, $3 permission to name if it fails
# Fails ONLY on an authorization error, not on "not found".
#
# Needed for an endpoint that legitimately 404s before the first apply. A plain
# cf_probe there would report a missing permission the token already has, and a
# preflight that cries wolf is one people learn to skip.
#
# $1 url, $2 description, $3 permission to name if it fails
cf_probe_auth() {
  local url="$1" what="$2" permission="$3"
  local body
  body="$(curl -s -H "Authorization: Bearer ${TF_VAR_cloudflare_api_token}" "$url" || true)"

  if printf '%s' "$body" | grep -qiE 'not authorized|Authentication error|Invalid request headers'; then
    bad "$what" "add to the token: $permission"
  else
    pass "$what"
  fi
}

cf_probe() {
  local url="$1" what="$2" permission="$3"
  local body
  body="$(curl -s -H "Authorization: Bearer ${TF_VAR_cloudflare_api_token}" "$url" || true)"

  if printf '%s' "$body" | grep -q '"success":[[:space:]]*true'; then
    pass "$what"
  else
    local msg
    msg="$(printf '%s' "$body" | sed -n 's/.*"message":"\([^"]*\)".*/\1/p' | head -1)"
    bad "$what — ${msg:-no response}" "add to the token: $permission"
  fi
}

echo
echo "Preflight: $MODULE ($ENVIRONMENT)"
echo

case "$MODULE" in
  edge)
    : "${TF_VAR_cloudflare_api_token:?TF_VAR_cloudflare_api_token is not set — run: source ~/.xenopsbase.env}"
    SECRETS="$ROOT/infra/terraform/edge/env/$ENVIRONMENT.secrets.tfvars"
    VARS="$ROOT/infra/terraform/edge/env/$ENVIRONMENT.tfvars"
    ZONE="$(tfvar "$SECRETS" zone_id)"
    ACCOUNT="$(tfvar "$SECRETS" account_id)"

    if [ -z "$ZONE" ] || [ -z "$ACCOUNT" ]; then
      bad "zone_id / account_id not readable from $SECRETS" "copy env/secrets.tfvars.example and fill it in"
    else
      cf_probe "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records?per_page=1" \
        "DNS records" "Zone / DNS / Edit"
      cf_probe "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT/cfd_tunnel?per_page=1" \
        "Cloudflare Tunnel" "Account / Cloudflare Tunnel / Edit"

      # Only probed when the module will actually touch them. Requiring a
      # permission the configuration does not use would be its own false alarm.
      if [ "$(tfbool "$VARS" manage_zone_settings)" = "true" ]; then
        cf_probe "https://api.cloudflare.com/client/v4/zones/$ZONE/settings/ssl" \
          "Zone settings (manage_zone_settings = true)" "Zone / Zone Settings / Edit"
      fi
      if [ "$(tfbool "$VARS" manage_waf)" = "true" ]; then
        cf_probe "https://api.cloudflare.com/client/v4/zones/$ZONE/rulesets" \
          "WAF rulesets (manage_waf = true)" "Zone / Zone WAF / Edit"
      fi

      # A SEPARATE permission from Zone WAF, despite both being rulesets on the
      # same zone. Zone WAF covers http_request_firewall_custom; the transform
      # phases need Transform Rules. The token had the first and not the second,
      # so `terraform plan` was clean and the apply failed with nothing more
      # specific than "request is not authorized".
      cf_probe_auth "https://api.cloudflare.com/client/v4/zones/$ZONE/rulesets/phases/http_request_late_transform/entrypoint" \
        "Request header transform (X-Forwarded-Port)" "Zone / Transform Rules / Edit"

      # Access is ACCOUNT-scoped, not zone-scoped, so it is a different
      # permission again from everything above. Probed only when the module
      # will actually create an application.
      if [ "$(tfbool "$VARS" manage_access)" = "true" ]; then
        cf_probe "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT/access/apps?per_page=1" \
          "Access applications (manage_access = true)" "Account / Access: Apps and Policies / Edit"
        cf_probe "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT/access/service_tokens?per_page=1" \
          "Access service tokens (manage_access = true)" "Account / Access: Service Tokens / Edit"
        # No probe for access/organizations, deliberately. Terraform does not
        # manage the organisation, so failing a preflight over a permission the
        # apply never uses is the cry-wolf case cf_probe_auth exists to avoid.
        # Listing apps and service tokens is already evidence Zero Trust works.
      fi
    fi
    ;;

  mail-dns)
    : "${TF_VAR_cloudflare_api_token:?TF_VAR_cloudflare_api_token is not set}"
    ZONE="$(tfvar "$ROOT/infra/terraform/mail-dns/mail.secrets.tfvars" zone_id)"
    if [ -z "$ZONE" ]; then
      bad "zone_id not readable from mail.secrets.tfvars" "copy mail.secrets.tfvars.example and fill it in"
    else
      cf_probe "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records?per_page=1" \
        "DNS records on the mail zone" "Zone / DNS / Edit"

      # The commonest mistake here is not a missing permission but the WRONG
      # TOKEN: the edge one is scoped to a different account entirely, so it
      # authenticates fine and simply cannot see this zone.
      if ! curl -s -H "Authorization: Bearer ${TF_VAR_cloudflare_api_token}" \
           "https://api.cloudflare.com/client/v4/zones/$ZONE" | grep -q '"success":[[:space:]]*true'; then
        bad "the token cannot see zone $ZONE" \
            "this module needs the MAIL zone token, not the edge one — they are on different accounts"
      fi
    fi
    ;;

  cluster)
    : "${TF_VAR_hcloud_token:?TF_VAR_hcloud_token is not set — run: source ~/.xenopsbase.env}"
    if curl -s -H "Authorization: Bearer ${TF_VAR_hcloud_token}" \
         "https://api.hetzner.cloud/v1/servers?per_page=1" | grep -q '"servers"'; then
      pass "Hetzner Cloud API"
    else
      bad "Hetzner Cloud API rejected the token" "TF_VAR_hcloud_token must be a READ-WRITE token for THIS project"
    fi

    # A project-scoped token that is valid but points at the wrong project reads
    # as a working credential right up until it builds a cluster somewhere
    # unexpected, or fails to find one it was asked to destroy.
    NAMES="$(curl -s -H "Authorization: Bearer ${TF_VAR_hcloud_token}" \
      "https://api.hetzner.cloud/v1/servers?per_page=50" |
      sed -n 's/.*"name":"\([^"]*\)".*/\1/p' | head -20 || true)"
    if [ -n "$NAMES" ] && ! printf '%s' "$NAMES" | grep -q "xenopsbase"; then
      bad "the Hetzner token sees no xenopsbase servers" \
          "it may belong to another project — check before applying"
    fi

    if [ "$(tfvar "$ROOT/infra/terraform/cluster/env/$ENVIRONMENT.tfvars" node_transport_mode)" = "tailscale" ]; then
      if [ -n "${TF_VAR_tailscale_auth_key:-}" ]; then
        pass "Tailscale auth key present (node_transport_mode = tailscale)"
        echo "      note: it must be REUSABLE — a single-use key registers only the first node,"
        echo "            and the rest hang rather than fail"
      else
        bad "TF_VAR_tailscale_auth_key is not set, but node_transport_mode = tailscale" \
            "nodes cannot join the tailnet, and provisioning hangs rather than failing"
      fi
    fi
    ;;

  storage)
    : "${TF_VAR_hetzner_s3_access_key:?TF_VAR_hetzner_s3_access_key is not set}"
    : "${TF_VAR_hetzner_s3_secret_key:?TF_VAR_hetzner_s3_secret_key is not set}"
    pass "Hetzner S3 credentials present"
    ;;

  *)
    echo "unknown module: $MODULE" >&2
    exit 2
    ;;
esac

echo
if [ "$fail" -ne 0 ]; then
  echo "Preflight FAILED — nothing has been changed."
  echo "Fix the above, then re-run. This check exists so a scope problem stops"
  echo "here rather than halfway through an apply, with some resources created."
  exit 1
fi

echo "Preflight passed — the token can reach every API this module uses."
echo "(Read probes only; Cloudflare's Edit implies Read, so this cannot prove write access.)"
