-- V3 — document metadata.
--
-- Objects live in the bucket; this table is the index over them. The two are
-- separate systems with no shared transaction, so the consistency story is
-- written into the schema rather than assumed:
--
--   status = 'PENDING'    a row exists, the object may not. The client has been
--                         handed a presigned URL and may never use it.
--   status = 'AVAILABLE'  the object was confirmed present by a HEAD after
--                         upload. Only these are downloadable.
--
-- The ordering is deliberate. The row is created BEFORE the object, so the
-- failure mode is a row without an object -- which is invisible to users and
-- reapable -- rather than an object without a row, which is unreferenced data
-- nobody can find, delete, or account for.
--
-- object_key is generated server-side and never derived from the uploaded
-- filename. A key built from user input is a path-traversal and collision
-- surface, and object stores have no notion of a "directory" to escape from,
-- so the usual defences do not apply.

CREATE TABLE document (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_key      varchar(512) NOT NULL,
    filename        varchar(255) NOT NULL,
    content_type    varchar(255) NOT NULL,
    size_bytes      bigint,
    owner           varchar(255) NOT NULL,
    status          varchar(20)  NOT NULL,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    completed_at    timestamptz,

    CONSTRAINT uk_document_object_key UNIQUE (object_key),
    CONSTRAINT ck_document_status CHECK (status IN ('PENDING', 'AVAILABLE'))
);

-- Listing is always scoped to the caller, so the index leads with owner.
CREATE INDEX ix_document_owner_created_at ON document (owner, created_at DESC);

-- Supports the reaper that removes rows whose upload never completed. Partial,
-- because AVAILABLE rows are the overwhelming majority and never need scanning.
CREATE INDEX ix_document_pending_created_at ON document (created_at) WHERE status = 'PENDING';
