-- V4 — idempotency records for unsafe requests (T-3.8).
--
-- A client that sends POST and never sees the response cannot know whether it
-- happened. Retrying risks doing it twice; not retrying risks not doing it at
-- all. An idempotency key lets the client retry safely: the server recognises
-- the key, and replays the original response instead of acting again.
--
-- The stored response is the point. Returning a fresh 200 to a retry would be
-- wrong in a specific way -- the client would see success without ever learning
-- the id of the thing that was created the first time.

CREATE TABLE idempotency_record (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Client-supplied, and NEVER trusted alone. The scope below is what stops
    -- one caller guessing another caller's key and reading back their response.
    idempotency_key varchar(255) NOT NULL,

    -- The authenticated principal. Keys are unique per caller, not globally:
    -- two users independently choosing "1" must not collide, and neither must
    -- be able to observe that the other did.
    scope           varchar(255) NOT NULL,

    -- SHA-256 of method + path + body. A key replayed against a DIFFERENT
    -- request is a client bug, and answering it with the original response
    -- would hide that bug behind a plausible success.
    -- varchar, not char(64). Postgres reports char as `bpchar`, which Hibernate's
    -- schema validation rejects against a plain String field -- caught by the test
    -- profiles running ddl-auto: validate (#142). char would also pad with spaces,
    -- which is silently wrong for a value being compared for equality.
    request_hash    varchar(64)  NOT NULL,

    state           varchar(20)  NOT NULL,

    response_status integer,
    response_body   text,
    response_type   varchar(255),

    created_at      timestamptz  NOT NULL DEFAULT now(),
    completed_at    timestamptz,

    -- The concurrency control. Two simultaneous retries race to INSERT; exactly
    -- one wins and the loser gets a constraint violation, which the filter reads
    -- as "already in flight" and answers with 409. Doing this with a SELECT then
    -- an INSERT would let both pass the check and both act.
    CONSTRAINT uk_idempotency_key_scope UNIQUE (idempotency_key, scope),
    CONSTRAINT ck_idempotency_state CHECK (state IN ('IN_PROGRESS', 'COMPLETED'))
);

-- Supports the reaper. Records are only useful for as long as a client might
-- retry; keeping them forever turns a convenience table into the largest one in
-- the database.
CREATE INDEX ix_idempotency_created_at ON idempotency_record (created_at);
