-- V2 — the throwaway example table.
--
-- DELETE THIS when you delete ExampleItem, by adding a NEW migration that drops
-- the table. Do not edit or remove this file: Flyway records a checksum per
-- version, so changing an applied migration makes every environment that
-- already ran it fail validation on the next start.
--
-- Written BEFORE the entity, which is the order ddl-auto=validate enforces.
-- The reverse order appears to work against an empty database and fails
-- everywhere that already has data.

CREATE TABLE example_item (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(200) NOT NULL,
    created_at timestamptz  NOT NULL DEFAULT now()
);
