-- V5 — the four extension seams (T-3.10).
--
-- Each of these is cheap now and expensive later, which is the only reason a
-- template carries them. Adding audit columns to a populated table means
-- deciding what created_by holds for a million rows nobody recorded. Adding
-- soft delete after code has been written against hard delete means auditing
-- every query. Adding a tenant column after go-live means a migration that
-- cannot be rolled back safely.
--
-- None of them carry business semantics. They are shapes, not decisions.

-- ---------------------------------------------------------------------------
-- 1. Audit columns
--
-- created_by / last_modified_by hold the OIDC `sub`, not a username. A username
-- is mutable in Keycloak: record it here and renaming a user detaches them from
-- everything they did, or -- worse -- reattaches their history to whoever takes
-- the name next. An audit trail that can be rewritten by a profile edit is not
-- an audit trail.
--
-- 50 characters fits a UUID sub (36) with room for other issuers' formats.
-- ---------------------------------------------------------------------------

ALTER TABLE example_item
    ADD COLUMN created_by         varchar(50)  NOT NULL DEFAULT 'system',
    ADD COLUMN created_date       timestamptz  NOT NULL DEFAULT now(),
    ADD COLUMN last_modified_by   varchar(50),
    ADD COLUMN last_modified_date timestamptz;

ALTER TABLE document
    ADD COLUMN created_by         varchar(50)  NOT NULL DEFAULT 'system',
    ADD COLUMN created_date       timestamptz  NOT NULL DEFAULT now(),
    ADD COLUMN last_modified_by   varchar(50),
    ADD COLUMN last_modified_date timestamptz;

-- The DEFAULT exists only to make this migration possible against existing
-- rows. New rows get their value from the application, and 'system' in a fresh
-- row means the auditing wiring is not reaching that write path.

-- ---------------------------------------------------------------------------
-- 2. Audit log
--
-- ONE table for every entity, rather than a *_AUD table per entity as Hibernate
-- Envers does. Envers is the better-known answer and was considered; it was
-- rejected for a template on one specific ground: it needs a new migration for
-- every new entity, and forgetting that migration produces an entity with NO
-- audit trail and no error. A seam that can be silently skipped is not a seam.
--
-- The cost of this choice is that the payload is JSON rather than typed
-- columns, so querying "every row where status changed to X" is a JSON query
-- rather than a column predicate. That is the right trade for a template: it
-- keeps the mechanism uniform and impossible to forget.
-- ---------------------------------------------------------------------------

CREATE TABLE audit_log (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    entity_type varchar(255) NOT NULL,
    entity_id   varchar(255) NOT NULL,
    action      varchar(20)  NOT NULL,

    -- The immutable identifier, for attribution that survives a rename.
    actor       varchar(50)  NOT NULL,
    -- A POINT-IN-TIME snapshot of the display name. Correct to store precisely
    -- because it is a snapshot: it records what the username was when the action
    -- happened, which is what a human reading the log needs, and it makes no
    -- claim to still be current.
    actor_name  varchar(255),

    occurred_at timestamptz  NOT NULL DEFAULT now(),

    -- What changed. Null on delete, where the interesting fact is that it
    -- happened rather than what the values were.
    payload     jsonb,

    CONSTRAINT ck_audit_log_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE'))
);

-- "Everything that happened to this thing" is the query an audit log exists to
-- answer, so it is the one that gets an index.
CREATE INDEX ix_audit_log_entity ON audit_log (entity_type, entity_id, occurred_at DESC);
CREATE INDEX ix_audit_log_actor ON audit_log (actor, occurred_at DESC);

-- ---------------------------------------------------------------------------
-- 3. Soft delete
--
-- Demonstrated on example_item, the throwaway entity, rather than on document.
-- Soft-deleting a document would be actively wrong: its bytes live in object
-- storage, and a row that says "deleted" while the object still exists and
-- still costs money is a leak wearing a tombstone.
--
-- That asymmetry is the point. Soft delete is not a default to apply
-- everywhere; it is a per-entity decision, and the seam exists so the decision
-- is cheap either way.
-- ---------------------------------------------------------------------------

ALTER TABLE example_item
    ADD COLUMN deleted boolean NOT NULL DEFAULT false;

-- Partial index: live rows are the overwhelming majority and every ordinary
-- query filters to them. Indexing the deleted ones would cost writes to serve
-- a query nobody runs in a hot path.
CREATE INDEX ix_example_item_live ON example_item (id) WHERE deleted = false;

-- ---------------------------------------------------------------------------
-- 4. Multi-tenancy
--
-- A discriminator column, present and inert. Every row gets 'default' until a
-- resolver says otherwise, so nothing behaves differently today.
--
-- NOT NULL with a default on purpose. A nullable tenant column is the failure
-- mode this seam exists to avoid: one code path forgets to set it, those rows
-- match no tenant filter, and they become invisible to every tenant including
-- the one that owns them.
-- ---------------------------------------------------------------------------

ALTER TABLE example_item
    ADD COLUMN tenant_id varchar(64) NOT NULL DEFAULT 'default';

CREATE INDEX ix_example_item_tenant ON example_item (tenant_id);

-- ---------------------------------------------------------------------------
-- 5. Transactional outbox
--
-- Written in the SAME transaction as the change it describes. That is the whole
-- mechanism: a message and the state change it announces either both commit or
-- neither does. Publishing to a broker directly from application code cannot
-- offer that -- the commit and the publish are two systems, and any ordering of
-- them has a window where one happened and the other did not.
-- ---------------------------------------------------------------------------

CREATE TABLE outbox_message (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- What kind of thing happened, and to what. Deliberately strings: an outbox
    -- that knows about domain types couples the plumbing to the domain.
    message_type   varchar(255) NOT NULL,
    aggregate_type varchar(255) NOT NULL,
    aggregate_id   varchar(255) NOT NULL,

    payload        jsonb        NOT NULL,

    -- Carried through to the published message so a consumer's logs can be
    -- joined to the request that caused the event (T-3.8).
    correlation_id varchar(64),

    created_at     timestamptz  NOT NULL DEFAULT now(),
    published_at   timestamptz,

    -- Delivery is at-least-once. A relay can publish and then fail before
    -- marking the row, so the same message can be sent twice; consumers must be
    -- idempotent. Exactly-once is not available here and pretending otherwise
    -- would be the more dangerous choice.
    attempts       integer      NOT NULL DEFAULT 0,
    last_error     text
);

-- The relay's only query: unpublished, oldest first. Partial, because published
-- rows are the majority and are never scanned.
CREATE INDEX ix_outbox_unpublished ON outbox_message (created_at) WHERE published_at IS NULL;
