-- V8 — the platform probe (T-9.2).
--
-- ONE table, replacing `document` and `example_item`, and it is not a domain
-- entity. It is the template's self-test: the row every seam this stemcell
-- ships gets exercised against, so that smoke.sh, the k6 suites and the restore
-- drill are testing something rather than passing because nothing is left.
--
-- Every seam is here, on one table, which is the whole reason there is one
-- table rather than two:
--
--   audit columns          created_by / created_date / last_modified_*
--   audit_log              written by the Hibernate event listener (V5)
--   soft delete            `deleted`, below
--   multi-tenancy          `tenant_id`, present and inert
--   transactional outbox   written by PlatformProbeService in the same tx
--   idempotency            the filter, on the POST that creates a row here
--   object storage         `object_key`, and the PENDING/AVAILABLE dance
--
-- THE CONSISTENCY STORY, unchanged from the table this replaces because the
-- problem is unchanged. This row and the object it describes are in two systems
-- with no shared transaction:
--
--   status = 'PENDING'    a row exists, the object may not. The client has been
--                         handed a presigned URL and may never use it.
--   status = 'AVAILABLE'  the object was confirmed present by a HEAD after
--                         upload. Only these are downloadable.
--
-- The ordering is deliberate. The row is created BEFORE the object, so the
-- failure mode is a row without an object -- invisible to users and reapable --
-- rather than an object without a row, which is unreferenced data nobody can
-- find, delete, or account for.
--
-- object_key is generated server-side and never derived from `label`. A key
-- built from user input is a path-traversal and collision surface, and object
-- stores have no notion of a "directory" to escape from, so the usual defences
-- do not apply.

CREATE TABLE platform_probe (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    object_key         varchar(512) NOT NULL,
    label              varchar(255) NOT NULL,
    content_type       varchar(255) NOT NULL,
    size_bytes         bigint,
    owner              varchar(255) NOT NULL,
    status             varchar(20)  NOT NULL,
    created_at         timestamptz  NOT NULL DEFAULT now(),
    completed_at       timestamptz,

    -- Soft delete (T-3.10). Hibernate rewrites DELETE into an UPDATE of this
    -- column and adds `deleted = false` to every query it generates, so
    -- ordinary repository code cannot forget it.
    --
    -- SAFE HERE IN A WAY IT WAS NOT SAFE ON `document`, and the difference is
    -- worth stating because V5 said the opposite. The objection was that a row
    -- marked deleted while its object still exists is a leak wearing a
    -- tombstone: it costs storage and stays readable to anyone holding an
    -- unexpired presigned URL. PlatformProbeService answers it rather than
    -- ignoring it -- the OBJECT is deleted for real, immediately, in the same
    -- operation that tombstones the row. The bytes are what leak; the row is
    -- what has history worth keeping.
    deleted            boolean      NOT NULL DEFAULT false,

    -- Multi-tenancy (T-3.10). NOT NULL with a default on purpose: a nullable
    -- tenant column is the failure this seam exists to avoid -- one code path
    -- forgets to set it, those rows match no tenant filter, and they become
    -- invisible to every tenant including the one that owns them.
    tenant_id          varchar(64)  NOT NULL DEFAULT 'default',

    -- Audit columns, from AbstractAuditingEntity, declared exactly as V5 declared
    -- them on the tables this replaces. created_by / last_modified_by hold the
    -- OIDC `sub`, not a username: a username can be changed in Keycloak, and an
    -- audit trail that points at a name somebody else now holds is worse than no
    -- audit trail.
    --
    -- 'system' as the default rather than NULL, because a write with no
    -- authenticated principal is a real case -- a startup task, a migration --
    -- and "the system did it" is a truthful answer where NULL is an unanswered
    -- question in a column whose whole job is to answer it.
    created_by         varchar(50)  NOT NULL DEFAULT 'system',
    created_date       timestamptz  NOT NULL DEFAULT now(),
    last_modified_by   varchar(50),
    last_modified_date timestamptz,

    CONSTRAINT uk_platform_probe_object_key UNIQUE (object_key),
    CONSTRAINT ck_platform_probe_status CHECK (status IN ('PENDING', 'AVAILABLE'))
);

-- The listing index, and it is (owner, status, created_at DESC) rather than
-- (owner, created_at DESC) because V6 already paid for that lesson on the table
-- this replaces. The predicate is owner AND status; leaving status out made the
-- query walk the index newest-first and visit the heap for every row to check
-- it, and PENDING rows -- which accumulate, because the reaper is deliberately
-- not scheduled -- sort to the FRONT. Measured then: 37.5ms at 18 rows, 87.9ms
-- at 37,000 with no writes in flight at all.
--
-- Column order is the equalities first, then the sort key. The reverse serves
-- neither.
CREATE INDEX ix_platform_probe_owner_status_created_at ON platform_probe (owner, status, created_at DESC);

-- Backs the reaper for uploads that were presigned and never completed. Partial,
-- because AVAILABLE rows are the overwhelming majority and never need scanning,
-- and it carries no owner because the reaper does not scope by one.
CREATE INDEX ix_platform_probe_pending_created_at ON platform_probe (created_at) WHERE status = 'PENDING';

-- Live rows are the overwhelming majority and every ordinary query filters to
-- them, so the soft-delete index is partial for the same reason V5's was.
CREATE INDEX ix_platform_probe_live ON platform_probe (id) WHERE deleted = false;

CREATE INDEX ix_platform_probe_tenant ON platform_probe (tenant_id);
